delphix/zfs

- debian/tree/zfs-modules/etc/depmod.d/zfs-modules-_KVERS_.conf.in
> LX-1332 Wrong ZFS module loaded after git zfs-load

- include/libzfs.h
- lib/libzfs/libzfs_changelist.c
- lib/libzfs/libzfs_iter.c
- tests/runfiles/linux.run
- tests/zfs-tests/tests/functional/cli_root/zfs_unmount/Makefile.am
- tests/zfs-tests/tests/functional/cli_root/zfs_unmount/zfs_unmount_nested.ksh
This commit is to be merged once https://github.com/zfsonlinux/zfs/pull/7991 is accepted into ZoL.
It reverts the original revert from the commit that was hurting our internal testing.
Its goal is to get us back on track with merging without conflicts.
>  Revert "Revert "changelist should be able to iter on mounts""

- lib/libshare/libshare.c
- module/zfs/dsl_pool.c
ran: `git zfs-make -p -m <VM>`
> style-check fixes for delphix/zfs

- cmd/zfs/zfs_main.c
- include/sys/dbuf.h
- include/sys/dmu_zfetch.h
- lib/libzfs/libzfs_sendrecv.c
- module/zfs/dbuf.c
- module/zfs/dmu.c
- module/zfs/dmu_zfetch.c
- module/zfs/dnode.c
- module/zfs/dnode_sync.c
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1582/
zfs-precommt: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4635/
> Merge dbuf

- man/man8/zfs-program.8
- module/zfs/zcp_iter.c
- tests/zfs-tests/tests/functional/channel_program/synctask_core/cleanup.ksh
- tests/zfs-tests/tests/functional/channel_program/synctask_core/setup.ksh
- tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_bookmarks.ksh
- tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_holds.ksh
- tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_user_props.ksh
zfs-precommit: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4717/  (pending)
> Fix build breakage due to ZCP Holds and Bookmarks API in ZoL

- include/spl/sys/debug.h
- include/sys/dsl_dataset.h
- module/zfs/dbuf.c
- module/zfs/dmu_recv.c
- module/zfs/dsl_dataset.c
- module/zfs/vdev_indirect.c
- module/zfs/zfs_ioctl.c
- tests/zfs-tests/cmd/get_diff/.gitignore
This makes our codebase look more like upstream, so that there will be
less merge conflicts when merging future changes from upstream.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4682/ (in progress)
> rectify minor differences with upstream

- tests/zfs-tests/cmd/mkholes/mkholes.c
Signed-off-by: Matthew Ahrens <mahrens@delphix.com>
> fix style errors in mkholes.c

- module/zfs/spa.c
After integrating DLPX-65483 "Set aside a metaslab for ZIL blocks", `zpool list` reports the pool size is smaller than it was before.  
To maintain the previous semantics, spa_prop_get_config() needs to include the embedded ZIL metaslabs' space in ZPOOL_PROP_SIZE,ALLOCATED,FREE.
Manual check of pool size before and after the changes, and with/without log device.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4796/ (in progress)
> DLPX-65985 test_post_verify_pool_properties fails after migration because pool size is different

- cmd/mount_zfs/mount_zfs.c
- cmd/zfs/zfs_main.c
- cmd/zinject/zinject.c
- cmd/zpool/zpool_main.c
- cmd/zpool/zpool_vdev.c
- lib/libzfs/libzfs_util.c
- module/zfs/dmu_diff.c
- module/zfs/dsl_scan.c
- tests/zfs-tests/tests/functional/cli_root/zfs_diff/zfs_diff_encrypted.ksh
Merge the changes that have no merge conflicts.
running http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4829/
> Merge upstream to Sept 24th

- module/zfs/btree.c
This PR backports the core node merge fix to 6.0/release.
External Issue ID: DLPX-66635
> Fix core node merge bug

- cmd/Makefile.am
- cmd/zfs_ids_to_path/.gitignore
- cmd/zfs_ids_to_path/Makefile.am
- cmd/zfs_ids_to_path/zfs_ids_to_path.c
- configure.ac
- debian/zfsutils-linux.install
Backport of #94 to 6.0/release
> Small program that converts a dataset id and an object id to a path

- cmd/zfs/zfs_main.c
The `zfs share -g` command will skip nfs exports that have their `canmount` property set to `noauto` but otherwise have a valid mountpoint.  For NPM filesystems the `canmount`  and `sync` properties are overridden. This causes the `zfs-share` service to drop their exports.
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2529/
Also installed the fix onto an engine that had the condition and the `zfs share -g` now correctly ignores `canmount=noauto` but it is mounted when filtering the datasets to export.
> DLPX-66733 zfs share -g should ignore ZFS_CANMOUNT_NOAUTO

- cmd/arc_summary/arc_summary3
- include/os/linux/zfs/sys/Makefile.am
- include/os/linux/zfs/sys/zfs_context_os.h
- include/sys/zfs_context.h
- lib/libspl/include/os/linux/sys/Makefile.am
- lib/libspl/include/os/linux/sys/zfs_context_os.h
- lib/libspl/include/sys/Makefile.am
- tests/zfs-tests/include/libtest.shlib
- tests/zfs-tests/include/properties.shlib
- tests/zfs-tests/tests/functional/cli_root/zfs_set/compression_001_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_set/property_alias_001_pos.ksh
- tests/zfs-tests/tests/functional/compression/compress_001_pos.ksh
- tests/zfs-tests/tests/functional/compression/compress_003_pos.ksh
- tests/zfs-tests/tests/functional/compression/compress_004_pos.ksh
- tests/zfs-tests/tests/functional/nopwrite/nopwrite_varying_compression.ksh
- tests/zfs-tests/tests/functional/rsend/rsend_012_pos.ksh
- tests/zfs-tests/tests/functional/rsend/send-c_recv_lz4_disabled.ksh
- tests/zfs-tests/tests/functional/rsend/send-c_stream_size_estimate.ksh
- tests/zfs-tests/tests/functional/rsend/send-c_verify_ratio.ksh
- tests/zfs-tests/tests/functional/rsend/send_realloc_encrypted_files.ksh
Some copyright refactoring caused a merge failure in libtest.shlib
(Tests currently running)
`git zfs-precommit`
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4966/
`git ab-pre-push --test-upgrade-from 5.3.6.0`
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2548/
> Merge failure

- module/zfs/dsl_bookmark.c
We get EOVERFLOW (which causes the "Value too large" message) from
zap_entry_read() when trying to read a ZAP entry and the provided buffer
is too small to hold the entire value. In this case we are doing
zap_lookup_impl() in the bookmark zap object (ds_bookmarks_obj).
The dsl_bookmark_phys_t is one word longer on Linux than on (our version
of) illumos. (The additional word is zbm_ivset_guid, used by the
encryption feature.) We aren't creating any bookmarks on linux (before
migration completes), but there are some additional code paths that can
result in updating existing bookmarks to use the new, larger size which
is incompatible with illumos.
Specifically, dsl_bookmark_sync_done() updates bookmarks that are at or
after the most recent snapshot, whenever there's a write to the dataset. …
> maintain existing bookmark zap entry length

- contrib/initramfs/conf-hooks.d/zfs
- module/os/linux/zfs/zpl_inode.c
- module/zfs/zfs_log.c
- module/zfs/zfs_replay.c
- tests/runfiles/linux.run
- tests/zfs-tests/tests/functional/tmpfile/.gitignore
- tests/zfs-tests/tests/functional/tmpfile/Makefile.am
- tests/zfs-tests/tests/functional/tmpfile/tmpfile_stat_mode.c
merge conflict with `contrib/initramfs/conf-hooks.d/zfs`.  I included both changes.  Ours was from https://github.com/delphix/zfs/pull/14.  Upstream was from https://github.com/zfsonlinux/zfs/pull/9723
testing in progress:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2596/
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4987/
> Merge initramfs

- cmd/zpool/zpool_main.c
- include/libzutil.h
- lib/libzfs/libzfs_util.c
- man/man8/zpool.8
- tests/runfiles/common.run
- tests/zfs-tests/include/commands.cfg
- tests/zfs-tests/include/libtest.shlib
- tests/zfs-tests/tests/functional/cli_root/zpool/Makefile.am
- tests/zfs-tests/tests/functional/cli_root/zpool/setup.ksh
- tests/zfs-tests/tests/functional/cli_root/zpool/zpool_colors.ksh
upstream and we both added new functions at the end of libzfs_util.c.  Include them both.
testing: just zfs-make
> Merge libzfs_util.c

- contrib/initramfs/conf-hooks.d/zfs
The comment from LX-1144 is out of date and misleading.
I discovered this after opening https://github.com/delphix/zfs/pull/134.
zfs-precommit: (pending)
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5122/
> Update comment of LX-1144 workaround

- module/zfs/zfs_ioctl.c
This commit merges in the latest commits from ZoL master, resolving some send/recv related merge conflicts in the process.
> Fix merge issues with ZoL/master

- include/os/linux/spl/sys/taskq.h
- include/sys/zfs_context.h
- lib/libzpool/taskq.c
- module/os/linux/spl/spl-taskq.c
- module/zfs/zio.c
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5178/flowGraphTable/
> DLPX-68998 [Backport of DLPX-68997 to 6.0.3.0] Improve performance of zio_taskq_member

- man/man5/zfs-module-parameters.5
- module/zfs/dmu_recv.c
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5181/flowGraphTable/
cc @tonynguien
> DLPX-69058 [Backport of DLPX-69057 to 6.0.3.0] Improve zfs receive performance by batching writes

- include/libzfs.h
- include/sys/zfs_rlock.h
- lib/libspl/include/os/freebsd/sys/param.h
- lib/libzfs/os/freebsd/libzfs_compat.c
- module/os/freebsd/zfs/zfs_vnops.c
- module/zfs/zfs_rlock.c
> Merge commit 'fb91f0367e91fb74a391f56d80fa3d3a9c6a2902' into master

- module/zfs/arc.c
Since #187, ARC waiters (arc_shrinker_scan() and arc_get_data_impl())
only wait for the specified amount of memory to be evicted.  Even though
this mechanism ensures that ARC eviction makes progress and the amount
of memory used by the ARC is decreasing, the system may still be very
low on free memory.
This is especially problematic when arc_shrinker_scan() is called in the
direct reclaim case.  Even when the system is very low on memory, the
kernel's shrinker code may only ask for one "batch" of pages (512KB) to
be evicted.  If concurrent allocations consume these pages, there may
still be insuficient free pages, and the OOM killer takes action.
This commit makes ARC waiters also wait until there is sufficient free
memory in the system before being woken.  This makes it much less likely …
> ARC waiters must wait for sufficient free memory

- module/os/linux/zfs/zvol_os.c
This patch was first created for 6.0 stage with the following
two commits:
37bb1ae Add tunable to make all zvol writes sync when sync=standard
5eeb595 DLPX-69299 [Backport of DLPX-69298 to 6.0.1.1] Data corruption after DE reboot if zfs sync=standard on zvols
- Change compiles
zfs-precommit: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5434/
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3898/
> Add tunable to make all zvol writes sync when sync=standard

- module/zfs/zcp.c
This is a clean cherry-pick of https://github.com/openzfs/zfs/pull/11190.
> DLPX-72744 [Backport of DLPX-71924] Support bundle fails to generate due to internal error

- cmd/zfs_file/.gitignore
This resolves a failure in `make codecheck`
> add cmd/zfs_file/.gitignore

- module/zfs/zio.c
On very fragmented pools, there may be no large free chunks in the
normal allocation class (e.g. ~64KB, the size of compressed indirect
blocks).  This will cause the allocation to fall back on the embedded
slog metaslab.  This can cause the embedded slog metaslab to become
full/fragmented enough that ZIL allocations fail, causing sync writes to
fall back on txg_wait_synced(), which is very very slow.
To address this problem, this commit makes allocations try to gang
before allowing the embedded slog metaslab to be used for normal
allocations.  Although ganging is slow (it's roughly 25% of normal
performance, because we do ~4 writes for each block), it's much better
than sync writes whose ZIL allocation fails, which can be 0.1% normal
performance (txg_wait_synced() could take 10 seconds …
> gang before embedded slog

- include/sys/dbuf.h
- include/sys/dmu_objset.h
- module/zfs/dbuf.c
- module/zfs/dmu.c
- module/zfs/dmu_objset.c
- module/zfs/dmu_recv.c
- module/zfs/dnode.c
- module/zfs/dnode_sync.c
- module/zfs/dsl_dataset.c
- module/zfs/dsl_pool.c
clean backport of https://github.com/openzfs/zfs/pull/11105
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5553/
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4474/
> Improve zfs receive performance with lightweight write

- cmd/zgenhostid/Makefile.am
- contrib/dracut/90zfs/module-setup.sh.in
- contrib/dracut/90zfs/zfs-env-bootfs.service.in
- contrib/dracut/90zfs/zfs-load-key.sh.in
- debian/zfsutils-linux.install
- lib/libzfs/libzfs_import.c
- lib/libzutil/Makefile.am
- lib/libzutil/zutil_import.c
- rpm/generic/zfs.spec.in
To merge the zgenhostid changes, we need to also modify our packaging, in `debian/zfsutils-linux.install`
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4656/
> merge: Install zgenhostid to sbindir

- cmd/zfs_object_agent/Cargo.toml
- cmd/zfs_object_agent/src/object_based_log.rs
- cmd/zfs_object_agent/src/pool.rs
add first version of processing frees.  Happens serially, entirely in one txg.
> background free

- cmd/zfs_object_agent/src/client.rs
- cmd/zfs_object_agent/src/main.rs
- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/server.rs
- include/os/linux/kernel/linux/mod_compat.h
- include/sys/fs/zfs.h
- include/sys/vdev_impl.h
- module/nvpair/fnvpair.c
- module/os/linux/zfs/Makefile.in
- module/os/linux/zfs/vdev_object_store.c
- module/zfs/vdev.c
> first steps connecting vdev to agent

- cmd/zfs_object_agent/src/main.rs
- cmd/zfs_object_agent/src/object_based_log.rs
- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/server.rs
This is mostly code cleanup in the Pool class.  I've also changed the interface with the kernel to assume that each socket connection will talk about only one pool.
> agent code cleanup

- cmd/zfs_object_agent/src/main.rs
- cmd/zfs_object_agent/src/object_based_log.rs
- cmd/zfs_object_agent/src/pool.rs
The frees can be processed over multiple txg's.  Probably doesn't totally work yet - e.g. frees that happen during the cleanup will be forgotten.
> async free

- cmd/zfs_object_agent/src/object_access.rs
- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/server.rs
- lib/libzfs/libzfs_crypto.c
- module/os/linux/zfs/vdev_object_store.c
- module/zfs/dmu.c
- module/zfs/uberblock.c
- module/zfs/zio.c
fix a bunch of bugs that show up under heavier load
> error handling

- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/server.rs
- cmd/zpool/zpool_main.c
- cmd/zpool/zpool_vdev.c
- include/libzutil.h
- include/sys/vdev_impl.h
- lib/libzutil/zutil_import.c
- module/os/linux/zfs/vdev_object_store.c
- module/zfs/metaslab.c
- module/zfs/spa.c
- module/zfs/vdev.c
- module/zfs/vdev_draid.c
- module/zfs/vdev_label.c
Here's the pool import changes!
> Enable zpool import for objstore pools

- etc/systemd/system/zfs-import-cache.service.in
Master PR: https://github.com/delphix/zfs/pull/253
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5180/
> DLPX-75119 [Backport of DLPX-73192 to 6.0.9.0] Establish appropriate systemd service dependencies for iSCSI initiator

- cmd/zfs_object_agent/Cargo.lock
- cmd/zfs_object_agent/Cargo.toml
- cmd/zfs_object_agent/client/src/main.rs
- cmd/zfs_object_agent/src/object_access.rs
- retry s3 connection errors
- exponential backoff starting at 100ms
- common code for s3 error handling of various API calls (put, get, delete)
> s3 connection error retry

- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/server.rs
- include/sys/vdev_impl.h
- module/os/linux/zfs/vdev_object_store.c
- module/zfs/spa.c
- module/zfs/vdev_label.c
Signed-off-by: Paul Dagnelie <pcd@delphix.com>
> get config at pool open, verify features

- module/os/linux/zfs/vdev_object_store.c
Fix zfs-make error by casting to char *
> Cast to signed char

- module/os/linux/zfs/vdev_object_store.c
- added socket call to shutdown socket connection
- agent thread restarts socket connection whenever `agent_read_all` returns an error status
- `vdev_object_store_open` waits for socket agent
- `vdev_object_store_close` now waits for agent thread to exit before closing.
- `vdev_object_store_close` handles multiple close requests
If the agent is not running then debug messages would look like this:
```
vdev_object_store.c:142:zfs_object_store_open(): zfs_object_store_open failed to connect: -2
vdev_object_store.c:152:zfs_object_store_open(): SOCKET OPEN(ffff8c0b9b6c0000): 0000000000000000
```
Once the agent is started:
```
vdev_object_store.c:147:zfs_object_store_open(): zfs_object_store_open, socket connection ready, ffff8c0b95e1ce00
vdev_object_store.c:152:zfs_object_store_open(): SOCKET …
```
> DOSE-147 kernel handle agent restart

- cmd/zfs_object_agent/Cargo.lock
- cmd/zfs_object_agent/Cargo.toml
- cmd/zfs_object_agent/src/object_access.rs
- cmd/zfs_object_agent/src/server.rs
- lib/libzutil/os/linux/zutil_import_os.c
Reopens https://github.com/delphix/zfs/pull/308 , which was closed by accident.
> try rusoto for list_objects

- cmd/zfs_object_agent/src/object_access.rs
- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/server.rs
- first infrastructure for getting properties
- allow unordered writes
> unordered writes

- cmd/zfs_object_agent/src/object_access.rs
- cmd/zfs_object_agent/src/server.rs
- lib/libzfs/libzfs_pool.c
- lib/libzutil/os/linux/zutil_import_os.c
This PR adds iterating through buckets to find the ones we can access when the agent receives a list_pools request without a specified bucket.
> List buckets when importing pools

- include/sys/vdev_impl.h
- include/sys/zio.h
- module/os/linux/zfs/vdev_object_store.c
- module/zfs/vdev_label.c
- module/zfs/zio.c
DOSE-148 reopen pool and reissue BEGIN_TXG command
DOSE-248 resume pool after agent restart
> resume I/O when agent restarts

- cmd/zfs_object_agent/Cargo.lock
- cmd/zfs_object_agent/README.md
- cmd/zfs_object_agent/src/base_types.rs
- cmd/zfs_object_agent/src/block_based_log.rs
- cmd/zfs_object_agent/src/zettacache.rs
Correctly log & restore chunk summary, so that the Index actually works after the Agent restarts.
> track chunks

- cmd/zfs_object_agent/src/block_access.rs
- cmd/zfs_object_agent/src/block_based_log.rs
- cmd/zfs_object_agent/src/extent_allocator.rs
- cmd/zfs_object_agent/src/object_access.rs
- cmd/zfs_object_agent/src/object_based_log.rs
- cmd/zfs_object_agent/src/object_block_map.rs
- cmd/zfs_object_agent/src/pool.rs
- cmd/zfs_object_agent/src/range_tree.rs
- cmd/zfs_object_agent/src/server.rs
- cmd/zfs_object_agent/src/zettacache.rs
Fix some nits identified by `cargo clippy`
> clippy nits

- cmd/zfs_object_agent/src/pool.rs
In `try_reclaim_frees`, the threshold check is block count based but we would prefer it to be based on bytes (true size we can free).
Change threshold check to be based on bytes now that stats for bytes are working.
Removed ~3GB worth of files and confirmed that `try_reclaim_frees` did trigger a reclaim and that it freed the expected amount:
```
[2021-07-07 23:14:03.231][::pool][INFO] reclaim: TXG(30667) starting; pending_frees_bytes=3268Mib, blocks_bytes=20417Mib, 903381 free blocks pending
[2021-07-07 23:14:03.502][::pool][INFO] reclaim: loaded 229731 freed blocks in 269ms
[2021-07-07 23:14:03.588][::pool][INFO] reclaim: loaded sizes for 20599 objects in 84ms
[2021-07-07 23:14:03.589][::pool][DEBUG] reclaim: consolidating 1808 objects into ObjectID(61069) to free 229667 blocks …
```
> Use bytes for try_reclaim_frees threshold

- cmd/zfs_object_agent/client/src/client.rs
- cmd/zfs_object_agent/client/src/main.rs
See title; relatively few changes here, most of which are pretty simple.
> Apply cargo clippy to client subdirectory

- include/sys/zio.h
- module/nvpair/nvpair.c
- module/os/freebsd/zfs/zfs_vnops_os.c
- module/os/linux/zfs/zfs_vnops_os.c
- module/os/linux/zfs/zpl_file.c
- module/zfs/dmu_redact.c
- module/zfs/zcp_synctask.c
- module/zfs/zil.c
- module/zfs/zio.c
- module/zfs/zvol.c
From commit e04210035eba31
16:09:38  Auto-merging module/zfs/dmu_redact.c
16:09:38  CONFLICT (content): Merge conflict in module/zfs/dmu_redact.c
There was Delphix specific content near the line that was changed (line 1236 in dmu_redact.c).
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5778/
> Fixed merge conflict

- Makefile.am
- config/Abigail.am
- lib/libnvpair/libnvpair.abi
- lib/libuutil/libuutil.abi
- lib/libzfs/libzfs.abi
- lib/libzfs_core/libzfs_core.abi
- lib/libzfsbootenv/libzfsbootenv.abi
Upstream updated the abicheck procedure in checkstyle.yaml (github actions), but we have removed this check.
Merge by taking our version (keeping it removed).
testing: [ab-pre-push](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6052/)
> Merge checkstyle.yaml
