lib/libzfs/libzfs_util.c
module/zfs/dmu.c

External-issue: LX-958
Signed-off-by: Matthew Ahrens <mahrens@delphix.com>

fix style of hole count code

---

module/zfs/dmu.c

On linux, SEEK_FILE / SEEK_HOLE are inaccurate if the file is dirty, in
which case they say that there are no holes.  To get the same behavior
as on illumos, we need to set zfs_dmu_offset_next_sync.
External-issue: LX-975
Signed-off-by: Matthew Ahrens <mahrens@delphix.com>
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-smoke/32627/consoleFull

StorageContainerFileImpl.getNextHole may be inaccurate

---

debian/rules

We need to configure the ZFS build with `--enable-debuginfo` in order to prevent some additional Linux optimizations (such as automatic inlining of functions) that are detrimental to debugging.
Note that this is different from `--enable-debug` which enables `-DDEBUG` and has a heavy impact on performance.
This change mirrors a similar change we did in git-zfs-make/load.
http://collins.d.delphix.com:32423/job/devops-gate/job/projects/job/dx4linux/job/zfs-package-build/job/master/job/pre-push/21/console

LX-1103 Build ZFS packages with debuginfo

---

debian/control
debian/control.in
debian/control.modules.in

We want to create a "delphix-zfs" meta-package, so that it can be referenced in appliance-build to install all our zfs packages.
Note that currently we just install all the debs produced by the ZFS build job (with the debs with do not want to install deleted), but we are moving away from this logic. Instead we'll be adding our zfs packages to a seed repository which will be then passed to live-build.
I'm also adding a new virtual package: delphix-zfs-modules to make sure that delphix-zfs pulls delphix kernel modules.
The changes must unfortunately be duplicated in both `control` and `control.in` because of how the packaging system is organized.
http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/zfs-package-build/job/master/job/pre-push/4/console
I've tested that …

LX-1118 Create a delphix-zfs meta-package

---

debian/zfs-modules-_KVERS_.install.in
debian/zfs-modules-_KVERS_.triggers.in
module/Makefile.in

The intention is to have our Delphix ZFS modules be prioritized over stock Ubuntu ZFS modules that come with the kernel.
Our original approach was to remove/dpkg-divert the modules provided by Ubuntu, however it comes at the cost of modifying the original kernel package.
There's a more elegant solution that leverages the depmod hierarchy on Linux systems, more specifically there's an order for where the system looks for kernel modules (see /etc/depmod.d/ubuntu.conf).
This change installs Delphix ZFS modules into `/lib/modules/KERNEL/updates/` instead of the default directory `extra/`.
* pre-push: http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/zfs-package-build/job/master/job/pre-push/8/console (pass)
* Build appliance with the new ZFS modules and check that …

install ZFS modules into updates directory

---

contrib/initramfs/conf-hooks.d/zfs

A workaround for the fact that Ubuntu's mkinitramfs script does not understand zfs on root (https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1661629). This change will make it possible to build an initrd for a kdump kernel, and thus allow us to gather crashdumps.
Because this makes initrd images larger, and because this workaround is only necessary when using zfs on root, this change probably isn't generally useful, so it should probably be kept specific to Delphix, and removed when the Ubuntu bug is fixed.
- Applied this change using `git zfs-make` and `git zfs-load`, then made sure I could successfully install the `kdump-tools` package, which builds an initrd for kdump as part of its post install scripts.

LX-1144 Set MODULES=most when building initramfs

---

debian/control
debian/control.in

This introduces a dependency in the zfstest package on `attr`, the lack
of which causes failures in the following tests:
features/large_dnode/large_dnode_002_pos
projectquota/projectid_003_pos
rsend/send_realloc_dnode_size
slog/slog_replay_fs
xattr/xattr_001_pos
xattr/xattr_003_neg
xattr/xattr_004_pos
xattr/xattr_005_pos
xattr/xattr_006_pos
xattr/xattr_007_neg
xattr/xattr_011_pos
xattr/xattr_013_pos

LX-1114 Missing utilities causing zfstest failures

---

debian/rules
debian/tree/zfs-modules/etc/depmod.d/zfs-modules-_KVERS_.conf.in
debian/zfs-modules-_KVERS_.install.in
module/Makefile.in

The objective of this change is to revert back the change that installs
ZFS modules into the updates directory, and instead provide a rule that
specifies where to look by default for each ZFS module.
Generate packages: http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/zfs-package-build/job/master/job/pre-push/20/console (pass)
Appliance-build: http://ops.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build/job/master/job/pre-push/128/console (pass)
Note that when I tested it manually, it seems like Delphix ZFS modules were used even without the overrides. Will need to investigate more why is that so.

override built-in zfs modules

---

module/zfs/dmu.c
module/zfs/metaslab.c
module/zfs/spa_misc.c
module/zfs/vdev_queue.c

This change reverts a couple of commits that previously modified tunable
parameters directly in our ZFS codebase. Now, with the integration of
delphix/appliance-build#91, we want to undo this work and rely on
appliance-build to set these tunable values correctly.

Rely on appliance-build to set tunables correctly

---

module/zfs/zfs_ioctl.c

Co-authored-by: Paul Dagnelie <pcd@delphix.com>
Calls to the `zfs_ioc_send_space` ioctl fail following the redacted send changes. We need to add the new nvlist fields to the zfs_ioc_key whitelist.
Ran the redacted_send zfs tests manually with `/usr/share/zfs/zfs-tests.sh -v -T redacted_send`.

Update zfs_ioc_key for zfs_ioc_send_space

---

module/zfs/dsl_dataset.c

This was a mismerge of the bookmark accounting code from https://github.com/delphix/zfs/pull/19
/home/mahrens/bookmark.sh
BB tests are TBD

LX-1345 Incremental replication send size grossly miscalculated

---

module/zfs/dsl_dataset.c

Pull delphix fix for bookmark leak into ZoL

dsl_dataset_hold_obj can leak bookmarks

---

man/man5/zfs-module-parameters.5
module/zfs/dmu_send.c

This change exposes the zfs_override_estimate_recordsize tunable as a module parameter.

Add size estimate override tunable to list of module parameters

---

lib/libzfs/libzfs_sendrecv.c
module/zfs/dmu_recv.c

These small fixes for raw receives will be part of the upstream redacted send/recv commits when they land, we should include them in our repo now to avoid merge conflicts or possible issues.

Fixes for raw receives

---

cmd/zfs/zfs_main.c
cmd/zpool/zpool_main.c
lib/libshare/libshare.c
lib/libzfs/libzfs_mount.c

This change provides a coarse-grain file lock to the `zfs` and `zpool` commands to prevent concurrent updates to the `/etc/dfs/sharetab` file.  The lock is grabbed whenever we to call `zfs set sharenfs` or when we `zpool destroy` or `zpool export` the pool. This is meant as a hack to allow our testing to complete successfully as it does not protect against concurrent updates when commands use `-o sharenfs` property to update the nfs settings. We rely on the fact that our stack currently only sets the `sharenfs` property by calling `zfs set`.

LX-1396 umount failed (part deux)

---

debian/changelog

We can leverage the `dch` command to auto-generate the appropriate changelog entry.
This change is should be pushed along with devops-gate TOOL-6540, as those 2 changes depend on each other.
http://collins.d.delphix.com:21968/job/devops-gate/job/master/job/zfs-package-build/job/master/job/pre-push/16/consoleFull

Simplify changelog

---

debian/rules
debian/zfsutils-linux.install

Fix issues with packaging following recent merge with upstream.
- Re-built packages, installed manually on a system and checked that arc_summary works.
- pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/356/
- By default `configure.sh` auto-detects which version of python to build against. We want to manually specify the version of python since our build environment is not the same as the runtime environment.
- Related git-utils change: https://jira.delphix.com/browse/TOOL-7032

DLPX-62162 ZFS fails to build following changes to move to python3

---

include/sys/dsl_pool.h
module/zfs/dsl_pool.c
module/zfs/spa.c

Upstream, the bookmark_v2 errata problem is being handled with respect to encryption by asking users to recreate their encrypted datasets. We can't ask our users to recreate all their bookmarks. As a result, we take this alternative approach; when the feature is enabled but not active during spa_sync, and either of its dependencies are active, we iterate over all the bookmarks in the pool and increment the v2 featureflag for each one that would have incremented either of the flags that depend on it.
This code was tested by moving pools from an Illumos VM to a linux VM with these bits loaded, and then enabling the feature and deleting bookmarks. Without these bits, that causes the kernel panic described in the bug report.  In addition, the changes passed ab-pre-push.

Handle BOOKMARK_V2

---

module/zfs/dmu_send.c

When merging the large dnode changes with the redacted send/recv changes, a bug slipped through. The dnode_phys_t copy logic in send_cb that stores a copy of the dnp in the internal send record was only copying the first slot worth of data. Large dnodes would not have all their data copied correctly, resulting in incorrect and inconsistent send streams when random memory was dumped as part of the bonus buffer.
This patch was tested against  existing ZoL unit tests that were previously flaky, and are now stable. Also passes style checks, zloop, and the rest of the zfs test suite.

Fix large dnode bug in zfs send

---

include/libzfs_core.h
include/sys/dmu_recv.h
lib/libzfs_core/libzfs_core.c
module/zfs/dmu_recv.c
module/zfs/zfs_ioctl.c

This change swaps the incoming REDACT and OBJECT_RANGE records if the send stream is being received from Illumos. This change is only applicable for Delphix customers, where the DRR_REDACT record had a different value in earlier releases. This has been tested in conjunction with appstack changes to handle the modified API. Pushing needs to be coordinated with those changes.

Handle record swapping between Linux and DxOS

---

etc/systemd/system/zfs-import-cache.service.in
etc/systemd/system/zfs-import-scan.service.in
etc/systemd/system/zfs-mount.service.in

The "zfs-mount.service" is responsible for mounting all ZFS datasets on
a Delphix appliance, including all domain0 mounts. On an appliance with
thousands of domain0 datasets (e.g. thousands of VDBs), it's expected
for the "zfs-mount.service" to take a relatively long time to start
(compared to most other bootup services). Thus, we don't want to cause
that to add latency to the entire bootup process, since lots (nearly
all) services have a dependency on "local-fs.target".
Thus, this change removes the "zfs-mount.service" dependency from the
"local-fs.target". This way, "local-fs.target" will start up, while the
domain0 mounts can proceed without blocking other bootup critical
services. This can safely be done because we rely on "/etc/fstab" for
mounting all of the root filesystem datasets, …

"local-fs.target" shouldn't depend on "zfs-mount.service"

---

debian/zfsutils-linux.postinst

The zfs-import-scan service will run only when `/etc/zfs/zpool.cache` is missing and perform `zpool import -aN -o cachefile=none`.
This service is very different from Illumos, where only pools in zpool.cache are loaded, so the behaviour of automatically importing pools that are not in zpool.cache is very unexpected for most folks at Delphix and can potentially cause issues to support, which expect that domain0 will not be imported when zpool.cache is removed.
During Illumos to Linux migration, zpool.cache is not carried over, so the zfs-import-scan service will kick-off. Due to how service dependencies are layed out, the delphix-migration service will also start at the same time, and both will attempt to import domain0. The zfs-import-scan service will always fail because it doesn't pass …

DLPX-64566 Migration failed due to failure to import domain0

---

include/sys/dmu_recv.h

This fixes a checkstyle error that came up after merging redacted send/recv from upstream.

Fix whitespace issue

---

cmd/zdb/zdb.c
configure.ac
include/sys/metaslab.h
include/sys/spa_log_spacemap.h
man/man5/zfs-module-parameters.5
man/man8/zdb.8
module/zfs/metaslab.c
module/zfs/spa.c
module/zfs/spa_log_spacemap.c
module/zfs/vdev_indirect.c
tests/runfiles/linux.run
tests/zfs-tests/tests/functional/Makefile.am
tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
tests/zfs-tests/tests/functional/log_spacemap/Makefile.am
tests/zfs-tests/tests/functional/log_spacemap/log_spacemap_import_logs.ksh
tests/zfs-tests/tests/functional/removal/removal_condense_export.ksh

Changes:
* introduction of log_spacemap_import_logs.ksh test case(we had this in illumos as part of DLPX-63385)
* further exposure of a few tunables
* a few nits for code structure and the deletion a few debugging routines
* Various man page additions/changes
zfs-precommit: (success, unrelated known zloop failure: DLPX-63193)
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4661/
ab-pre-push [for unit tests and appliance tests] (success):
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1702/flowGraphTable/

Log Spacemap Project [Merge From Upstream]

---

debian/zfsutils-linux.postinst
debian/zfsutils-linux.prerm
etc/systemd/system/50-zfs.preset.in

This service was integrated upstream with https://github.com/zfsonlinux/zfs/pull/8975, however it is disabled by default.
We want to enable it on the Delphix Engine as a prerequisite for https://jira.delphix.com/browse/DLPX-64724.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1813/

Enable zfs-volumes.target by default

---

cmd/zfs/zfs_main.c
etc/systemd/system/zfs-share.service.in
include/libzfs.h
include/libzfs_impl.h
lib/libshare/libshare.c
lib/libshare/libshare_impl.h
lib/libshare/nfs.c
lib/libshare/smb.c
lib/libspl/include/libshare.h
lib/libzfs/libzfs_mount.c
tests/zfs-tests/include/libtest.shlib
tests/zfs-tests/tests/functional/cli_root/zfs_share/zfs_share_001_pos.ksh

DLPX-63546 Deleting vdb with additional mount point provisioned from a staged dsource causes dsource stale filehandle
DLPX-64357 Oracle can abort with ESTALE file handles when a Linux DVE is rebooted (regression)
When the `nfs-server.service` restart, it will also restart the `zfs-share.service` and `nfs-mountd.service`. Since the `zfs-share.service` currently runs after the `nfs-server.service` it creates a gap where an NFS client could request an NFS mount for a filesystem which has not yet been shared. This can happen when the NFS server is restarted or the engine is rebooted.
To overcome this gap, this fix introduces a new option to `zfs share` which generates a file which is compatible with the NFS service. This file is named `/etc/exports.d/zfs.exports` and hold all the exported …

ESTALE file handles can occur when nfs-server restarts 

---

debian/zfsutils-linux.install
debian/zfsutils-linux.postinst
debian/zfsutils-linux.prerm
etc/systemd/system/50-zfs.preset.in
etc/systemd/system/Makefile.am
etc/systemd/system/zfs-share-cleanup.service.in
rpm/generic/zfs.spec.in

This adds a simple service to cleanup the `/etc/exports.d/zfs.exports` file after it's been consumed by the `nfs-server.service`. The idea behind this change is to make sure that nobody is confused by the fact that the `zfs.exports` file is only valid at the time the `zfs-share.service` runs and it will grow stale as more shares and unshares take place. 
This service should be removed when we do the the NFS sharing redesign.

DLPX-65453 delete /etc/exports.d/zfs.exports after it's used

---

tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg

In the specific test `"feature@log_spacemap"` is checked twice. I deleted one of the occurences and this file should no longer have diffs with upstream ZoL.
When this PR makes it to `delphix/zfs` and https://github.com/zfsonlinux/zfs/pull/9143 makes it to ZoL we should no longer have diffs in this file and `spa_log_spacemap.c`.
Precommit: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4709/

fix log spacemap mismerge

---

cmd/zdb/zdb.c
cmd/ztest/ztest.c
include/sys/spa.h
include/sys/spa_impl.h
include/sys/vdev.h
include/sys/vdev_impl.h
include/sys/zfs_debug.h
man/man5/zfs-module-parameters.5
module/zfs/metaslab.c
module/zfs/spa.c
module/zfs/spa_misc.c
module/zfs/vdev.c
module/zfs/vdev_removal.c
module/zfs/zfs_log.c
module/zfs/zio.c
module/zfs/zvol.c
tests/zfs-tests/tests/functional/alloc_class/alloc_class_013_pos.ksh
tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_014_neg.ksh
tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_015_neg.ksh

Note: we will want to get this upstream to ZoL as well, but need to add some code for dynamically adding/removing slog devices.  When adding a slog, we want to disable the embedded metaslabs, and when removing the last slog, we want to enable the embedded metaslabs.
Compared to the illumos code, the differences are:
* in zio_dva_allocate(), we need to take into account the "special" metaslab class
* this feature is on by default
* exposed the `zfs_max_embedded_slogs` tunable
* clean up `vdev_metaslab_init()` by moving the call to `vdev_metaslab_group_create()` to `zdb_leak_init_prepare_indirect_vdevs()`
Mixing ZIL and normal allocations has several problems:
1. The ZIL allocations are allocated, written to disk, and then a few
seconds later freed.  This leaves behind "holes" (free …

Set aside a metaslab for ZIL blocks

---

module/zfs/spa_misc.c

This is similar to DLPX-65985, but in this case the issue is that the space accounting at the DMU level (i.e. "zfs list") is not including the space in the embedded LOG metaslabs. We need to add this in spa_update_dspace().
Add the embedded log space in spa_update_dspace.
Note that `zpool list` output is the same, but `zfs list`'s `AVAIL` is different.
5.3:
```
$ zpool list -v test
NAME         SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
test        22.5G   167K  22.5G        -         -     0%     0%  1.00x  ONLINE  -
c2t1d0    7.50G  59.5K  7.50G        -         -     0%     0%
c2t2d0    7.50G    48K  7.50G        -         -     0%     0%
c2t3d0    7.50G  59.5K  7.50G        -         -     0%     0%
$ zfs list test
NAME   USED  AVAIL  REFER  MOUNTPOINT …
```

DLPX-66105 storageTotal of system info reduces after migration

---

module/zfs/dsl_scan.c

I'm suggesting that we "backport" this change from ZoL to 6.0, because it impacts correctness of scrubs and resilvers.
commit message:
```
The was incorrect with respect to swapping dataset IDs both in the
on-disk ZAP object and the in-memory queue.
In both cases, if ds1 was already present, then it would be first
replaced with ds2 and then ds would be replaced back with ds1.
Also, both cases did not properly handle a situation where both ds1 and
ds2 are already queued.  A duplicate insertion would be attempted and
its failure would result in a panic.
Reviewed-by: Matt Ahrens <matt@delphix.com>
Reviewed-by: Tom Caputi <tcaputi@datto.com>
Signed-off-by: Andriy Gapon <avg@FreeBSD.org>
Closes #9140 
Closes #9163
```
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precom …

Fix dsl_scan_ds_clone_swapped logic

---

module/zfs/dsl_scan.c

This issues fixes the scrub-related panics that we discovered during additional testing of the btree changes. Some of these errors would have been caught by additional compiler warning flags; these are being tested and may be introduced upstream.
Signed-off-by: Paul Dagnelie <pcd@delphix.com>

Fix dsl_scan issues

---

cmd/mount_zfs/mount_zfs.c
cmd/zfs/zfs_main.c
cmd/zinject/zinject.c
cmd/zpool/zpool_main.c
cmd/zpool/zpool_vdev.c
include/sys/Makefile.am
include/sys/dmu.h
include/sys/zvol.h
include/sys/zvol_impl.h
lib/libzfs/libzfs_util.c
module/os/linux/zfs/Makefile.in
module/os/linux/zfs/zvol_os.c
module/zfs/dmu_diff.c
module/zfs/dmu_objset.c
module/zfs/dsl_scan.c
module/zfs/zfs_ioctl.c
module/zfs/zvol.c
tests/zfs-tests/tests/functional/cli_root/zfs_diff/zfs_diff_encrypted.ksh

Merge commit '5df7e9d85ced424292e8312a7848b6092a29c930' into merge2
merge notes: I moved commit 883275865df4495e31585e4d7465a8eac8142857
"dx4linux: override phys block size" from module/zfs/zvol.c to
module/os/linux/zfs/zvol_os.c
zfs-precommit had some unrelated ZTS failures: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/4832/
running ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2259/
This is based on #80.  The unique changes can be seen here: https://github.com/delphix/zfs/commit/26bac0142bbe9cf76ac5cced3499d7b45993b336

merge upstream zvol restructuring

---

module/zfs/btree.c

This PR fixes a bug in the core node merge logic for the btree changes. This is already fixed upstream due to the rewrite that simplifies the merge and split logic. This change will need to be backported to 6.0.0.0
External Issue ID: DLPX-66564

Fix core node merge bug

---

debian/tree/zfsutils-linux/usr/lib/zfs-linux/share-cleanup
etc/systemd/system/zfs-share-cleanup.service.in

This is a follow on to [PR-64](https://github.com/delphix/zfs/pull/64) which introduced the `zfs share -g` CLI  variant and changed the `zfs-share` service to run _before_ the `nfs-server` service.  With than change, there is now a window from the time the `zfs-share` service generates the `zfs.exports` file and the `nfs-server` startup completes. A `zfs set sharenfs` operation within that window will silently not export the share.
Extend the zfs-share-cleanup service to re-generate a zfs.imports file and check for any changes. If there is a delta, we run `exportfs -r` to export the new additions.
`$ git ab-pre-push -k --test-upgrade-from 5.3.6.0 --tests`
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2338/
Manually tested that …

Add check for new shares to zfs-share-cleanup

---

cmd/Makefile.am
cmd/zfs_ids_to_path/.gitignore
cmd/zfs_ids_to_path/Makefile.am
cmd/zfs_ids_to_path/zfs_ids_to_path.c
configure.ac
debian/zfsutils-linux.install

This utility accepts a pool name, a dataset id, and an object id, and returns the path to that object. This is useful in a few situations, especially when using tracing tools that may not be able to iterate through an object heirarchy to derive a full path.

Small program that converts a dataset id and an object id to a path

---

debian/rules
debian/zfs-headers-_KVERS_.install.in

Previously we generated the files for the header package by copying
what's in `include` directory of the source tree.  Since the source file
restructuring for ZoF, the header files in the source code were
reorganized into platform-specific subdirectories (for Linux and
FreeBSD).  However, when installed, we want all the header files
together, as they were before the ZoF restructuring.
`make install` knows how to arrange the header files from the
platform-specific subdirectories into a single combined directory.  This
change leverages that to generate the directory structure for the header
package.  Specifically, we `make install -C include` into a temporary
directory, and then use that temporary directory to get the files for
the package.
git-ab-pre-push: …

ZFS header package should put files in one directory

---

debian/tree/zfsutils-linux/usr/lib/zfs-linux/share-cleanup

zfs-share-cleanup service has additional race conditions
1. In `zfs-share-cleanup` where shares are added after a new `zfs.exports` file is generated but before the `exportfs -r` is called.  This is addressed by using `exportfs -a`.
2. The is also a case where there are no shares (and thus no `zfs.exports` file) when `zfs-share` service runs but they are added before `zfs-share-cleanup` service runs.
git ab-pre-push --test-upgrade-from 5.3.6.0
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/upgrade-testing/2568/

DLPX-66916 zfs-share-cleanup service has additional race condition

---

cmd/zvol_wait/zvol_wait

zvol_wait waits for zvol links to be created under /dev/zvol for each zvol.
Links are not created for redacted zvols so we should ignore those.
This backports https://github.com/delphix/zfs/commit/1c47c2c42cdc809ce998d7a5b7b0df145201ad89.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2432/

[Backport from master] zvol_wait should ignore redacted zvols

---

cmd/zfs/zfs_main.c

**Backport of Issue DLPX-66733 to 6.0.0.0**
The `zfs share -g` command will skip nfs exports that have their `canmount` property set to `noauto` but otherwise have a valid mountpoint.  For NPM filesystems the `canmount`  and `sync` properties are overridden. This causes the `zfs-share` service to drop their exports.
git ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2529/
Also installed the fix onto an engine that had the condition and the `zfs share -g` now correctly ignores `canmount=noauto` but it is mounted when filtering the datasets to export.

DLPX-66733 Backport

---

include/sys/btree.h
module/zfs/btree.c
module/zfs/dsl_scan.c
module/zfs/range_tree.c

DLPX-67503
This is a simple backport of https://github.com/zfsonlinux/zfs/pull/9441 to 6.0.0.0

[Backport of Issue DLPX-67502 to 6.0.0.0] ztest crash in rs_get_start

---

module/zfs/dsl_bookmark.c

We get EOVERFLOW (which causes the "Value too large" message) from
zap_entry_read() when trying to read a ZAP entry and the provided buffer
is too small to hold the entire value. In this case we are doing
zap_lookup_impl() in the bookmark zap object (ds_bookmarks_obj).
The dsl_bookmark_phys_t is one word longer on Linux than on (our version
of) illumos. (The additional word is zbm_ivset_guid, used by the
encryption feature.) We aren't creating any bookmarks on linux (before
migration completes), but there are some additional code paths that can
result in updating existing bookmarks to use the new, larger size which
is incompatible with illumos.
Specifically, dsl_bookmark_sync_done() updates bookmarks that are at or
after the most recent snapshot, whenever there's a write to the dataset. …

6.0/release: maintain existing bookmark zap entry length

---

module/os/linux/zfs/zfs_znode.c

Internal Issue: DLPX-68284
Contains 2 commits: one that fixes the original issue, and one that fixes a regression introduced by the aforementioned commit.
Commit 1:
```
commit 41e1aa2a06f81640c3a3e1a6b12558d95887f662
Author: Heitor Alves de Siqueira <halves@canonical.com>
Date:   Fri Nov 15 14:56:05 2019 -0300
Break out of zfs_zget early if unlinked znode
If zp->z_unlinked is set, we're working with a znode that has been
marked for deletion. If that's the case, we can skip the "goto again"
loop and return ENOENT, as the znode should not be discovered.
Reviewed-by: Richard Yao <ryao@gentoo.org>
Reviewed-by: Matt Ahrens <mahrens@delphix.com>
Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov>
Signed-off-by: Heitor Alves de Siqueira <halves@canonical.com>
Closes #9583
```
Commit 2:
``` …
```

Backport of Issue DLPX-67868 to 6.0.1.0

---

module/zfs/metaslab.c

The memory limit for metaslab range trees was mismerged, it should be 25.

Fix mismerged memory limit

---

module/zfs/metaslab.c

This is a backport of an existing change for 6.0.1

Fix mismerged mem limit for range trees

---

include/sys/arc.h
include/sys/arc_impl.h
module/zfs/arc.c
module/zfs/dmu_send.c

merge this commit from upstream:
| * commit 1dc32a67e93bbc8d650943f1a460abb9ff6c5083
| | Author: Matthew Ahrens <mahrens@delphix.com>
| | Date:   Tue Mar 10 10:51:04 2020 -0700
| |
| |     Improve zfs send performance by bypassing the ARC
The conflict was due to an adjacent change in setup_reader_thread(): upstream has `minclsyspri` and we have `maxclsyspri`.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3060/

merge "Improve zfs send performance by bypassing the ARC"

---

module/zfs/zvol.c

http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5133/
See https://github.com/openzfs/zfs/pull/10163
Changes for the backport:
* changes apply to zvol.c, not zvol_os.c
* `rangelock_*`, not `zfs_rangelock_*`

DLPX-69204 [Backport of DLPX-69203 to 6.0.1.1] Improve ZVOL sync write performance by using a taskq

---

module/zfs/zvol.c

Make all zvol writes and discards sync unless sync=disabled is set. This is meant to avoid data corruption when exposing the zvols over iSCSI and the system reboots unexpectedly.
This work is split into 2 parts:
1. Adding a new tunable that, when set, makes sync=standard behave the same way as sync=always for zvols. This work can be upstreamed.
2. Enable the tunable for Delphix.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3185/

DLPX-69299 [Backport of DLPX-69298 to 6.0.1.1] Data corruption after DE reboot if zfs sync=standard on zvols

---

tests/zfs-tests/tests/functional/devices/devices_001_pos.ksh
tests/zfs-tests/tests/functional/devices/devices_002_neg.ksh
tests/zfs-tests/tests/functional/devices/devices_common.kshlib
tests/zfs-tests/tests/functional/devices/setup.ksh

devices_001_pos and devices_002_neg fail in 6.0/stage when run in aws using
the default instance size of DCoA.
This is a clean cherry pick of https://github.com/openzfs/zfs/pull/9773
from openzfs master. Currently, devices_001_pos and devices_002_neg fail due
to an awk regex that cannot handle the contents of /proc/partitions on nitro
instances because of nvme devices.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/run-zts/14/

ZTS: devices_001_pos and devices_002_neg

---

include/os/linux/kernel/linux/simd_x86.h

Clean cherry-pick from master.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5118/
The ZTS failure is an unrelated issue which @jwk404 is filing a bug for.
The ztest failure is also unrelated.
commit message:
fxsave and xsave require the target address to be 16-/64-byte aligned.
kmalloc(_node) does not (yet) offer such fine-grained control over
alignment[0,1], even though it does "the right thing" most of the time
for power-of-2 sizes. unfortunately, alignment is completely off when
using certain debugging or hardening features/configs, such as KASAN,
slub_debug=Z or the not-yet-upstream SLAB_CANARY.
Use alloc_pages_node() instead which allows us to allocate page-aligned
memory. Since fpregs_state is padded to a full page anyway, and this
code is only …

DLPX-69007 [Backport of DLPX-69006 to 6.0.2.0] SIMD: Use alloc_pages_node to force alignment

---

cmd/zpool/zpool_main.c
include/libzfs.h
lib/libzfs/libzfs_pool.c

This is a clean cherry-pick of the commit from master.
I tested it by doing a lot of zfs administrative actions, and then running `strace zpool history` and noting that it alternates between printing output and doing the history IOCTL.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5119/ (the zts failure is an unrelated issue which @jwk404 is filing)
Original commit message:
In original implementation, zpool history will read the whole history
before printing anything, causing memory usage goes unbounded. We fix
this by breaking it into read-print iterations.
Reviewed-by: Tom Caputi <tcaputi@datto.com>
Reviewed-by: Matt Ahrens <matt@delphix.com>
Reviewed-by: Igor Kozhukhov <igor@dilos.org>
Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov> …

DLPX-68992 [Backport of DLPX-68991 to 6.0.2.0] Fix zpool history unbounded memory usage

---

include/sys/arc.h
man/man5/zfs-module-parameters.5
module/os/linux/zfs/arc_os.c
module/zfs/arc.c

Merge Conflict Diff:
```
diff --cc module/zfs/arc.c
index 03ab5d0dc7,8a0c1a4a7e..0000000000
--- a/module/zfs/arc.c
+++ b/module/zfs/arc.c
@@@ -7150,15 -7150,13 +7150,25 @@@ arc_init(void
arc_lowmem_init();
#endif
++<<<<<<< HEAD
+      /* Set min cache to 1/32 of all memory, or 32MB, whichever is more */
+      arc_c_min = MAX(allmem / 32, 2ULL << SPA_MAXBLOCKSHIFT);
+      /* set max to 3/4 of all memory, or all but 1GB, whichever is more */
+      if (allmem >= 1 << 30)
+              arc_c_max = allmem - (1 << 30);
+      else
+              arc_c_max = arc_c_min;
+      arc_c_max = MAX(allmem * 3 / 4, arc_c_max);
+
++=======
+       /* Set min cache to 1/32 of all memory, or 32MB, whichever is more. */
+       arc_c_min = MAX(allmem / 32, 2ULL << SPA_MAXBLOCKSHIFT);
+
+       /* How to …
```

Fix Merge Conflict with the ARC

---

tests/zfs-tests/tests/perf/perf.shlib

This is a clean cherry-pick of Tony's upstream PR https://github.com/openzfs/zfs/pull/9847
ZFS performance tests don't create json output, making results hard to process.
Making the default FIO output format be JSON thus easier to post process
performance results. To get previous 'normal' output format,
PERF_FIO_FORMAT can be set prior to invoking zfs-tests.sh. For example:
'PERF_FIO_FORMAT=normal ./zfs-tests.sh -T perf -r ./runfiles/perf.run'
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-self-service/30899/consoleFull
I verified json output is being produced.

ZFS performance suite should use JSON fio output

---

module/zfs/dmu_send.c

Fixes an obvious issue of calling arc_buf_destroy() on an
unallocated arc_buf.
Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov>
Reviewed-by: Matt Ahrens <matt@delphix.com>
Reviewed-by: Paul Dagnelie <pcd@delphix.com>
Signed-off-by: Chris Dunlop <chris@onthe.net.au>
Closes #9453
Note: copied from original PR.
Fixes an obvious issue of calling arc_buf_destroy() on an unallocated arc_buf
Note: copied from original PR (with small edits).
The original issue was reported by @mattmacy in openzfs/zfs#9438 and a fix proposed.
This approach to fixing the issue is the outcome of the discussion in openzfs/zfs#9438, but it seems neither of us really know how the code is supposed to behave, thus a review from more knowledgeable contributors, hopefully including the original author @pcd1193182, is …

DLPX-68989 [Backport of DLPX-68988 to 6.0.2.0] Don't call arc_buf_destroy on unallocated arc_buf

---

debian/control
debian/control.in
debian/control.modules.in
debian/rules

= Motivation
We've recently been hitting issues where the crash-kernel runs out
of memory while its being bootstrapped after the main kernel panicks.
We could always keep increasing the memory reserved from the crash
kernel at the expense of the memory available to main kernel. For
customers that may not be an issue, but for developer VMs generally
provisioned with 8GB of memory the impact is higher. As a result,
I've been working on making our crash kernel lighter.
= Patch Description
The DWARF info from the ZFS-related kernel modules "dwarf"s in
size the sections of these binaries that are actually needed for
them to run. This patch splits the debug info of all the ZFS
modules into a separate debian package and strips down the original
modules. This way the initramfs of the original …

Split debug info of ZFS modules to separate package

---

module/zfs/arc.c
module/zfs/dmu_objset.c
module/zfs/mmp.c
module/zfs/spa.c
module/zfs/zio.c

http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5179/flowGraphTable/
cc @tonynguien

DLPX-68996 [Backport of DLPX-68995 to 6.0.3.0] Improve zfs destroy performance with zio_t-free zio_free()

---

module/os/linux/spl/spl-kmem-cache.c
module/os/linux/spl/spl-proc.c

This reverts commit f75dea29b3ac9a4d63017e6c8fc41b4896a8bc22.
We've hit a performance regression in this commit where running the
ZFS performance suite we've observed 1~8% slowdown. As the commit
was made purely for debugging purposes in a code path that doesn't
change often, the revert is pretty low-risk.
ran ab-pre-push:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3392/flowGraphTable/
(dx-test is known failure)
ran zfs-make and load on a VM and ensured that the change is gone by running `spl_kmem_caches` on SDB

Revert "Update skc_obj_alloc for spl kmem caches that are backed by Linux

---

module/os/linux/spl/spl-kmem-cache.c
module/os/linux/spl/spl-proc.c

This reverts commit f75dea29b3ac9a4d63017e6c8fc41b4896a8bc22.
We've hit a performance regression in this commit where running the
ZFS performance suite we've observed 1~8% slowdown. As the commit
was made purely for debugging purposes in a code path that doesn't
change often, the revert is pretty low-risk.
= Testing
ab-pre-push (pending): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3394/
`spl_kmem_caches` on sdb after `zfs-make` and `zfs-load`.

[Backport to 6.0/release] Revert "Update skc_obj_alloc for spl kmem caches that are backed by Linux

---

debian/control
debian/control.in
debian/control.modules.in
debian/rules

Original: https://github.com/delphix/zfs/pull/154
Pair commit needed in delphix-kernel: https://github.com/delphix/delphix-kernel/pull/13
Testing:
Did the exact same testing with original review for 6.0 - current VM holding all the changes is sd-60-split.dcenter

Backport: Split debug info of ZFS modules to separate package

---

module/Makefile.in

= Problem
Even though the debug info is split from the kernel modules
when they are packaged for the product, developers iterating
using git-zfs-{make,load} have to manually split the DWARF
info themselves and then recreate the crash kernel.
= Patch
This patch changes the modules_install target of the modules
Makefile that runs every time we do `make install` from the
root of the repo (git-zfs-load does that too). The code added
to the target is very similar to the one used in debian/rules
that provides the same functionality. Unfortunately that code
will have to stay duplicated unless we decide to do a major
refactoring in the debian directory where we can issen a
single `make install` command for all packages (userland,
headers, and modules) and everything will be placed and
packaged in …

Running `make install` should split debug info

---

debian/zfsutils-linux.cron.d

For our appliance, I'm proposing that we just comment out the cron entry to prevent automatic scrubs from being kicked off. Other possible solutions:
- remove the cron file from package
- update the scrub script to exclude some set of pools
I don't have a strong opinion one way or another so I've chosen the simplest approach.

DLPX-69914 disable automatic scrubs

---

lib/libzfs_core/libzfs_core.c

https://jira.delphix.com/browse/DLPX-69750
The commit that cherry-picked the upstream commit "Remove deduplicated
send/receive code" changed `lzc_receive_resumable_illumos()` to pass
`illumos=B_FALSE` instead of `illumos=B_TRUE`.  This breaks SDD
(redacted receive) from 5.3 to master.
Introduced by: e87eb86210f5c5d991634262f6b683b3a3a4d830
This problem is compounded by https://github.com/openzfs/zfs/pull/10320 "fix error handling in receive_writer_thread()", which causes this to result in incorrect on-disk state leading to this panic.  With that error handling fixed, the test fails, rather than panicking.  With both fixes, the test passes.
running sdd tests

DLPX-69750 PANIC in zfs_ioc_objset_stats_impl after redacted receive from illumos

---

cmd/Makefile.am
cmd/zfs_ids_to_path/zfs_ids_to_path.c
configure.ac
debian/zfsutils-linux.install
include/libzfs.h
lib/libzfs/libzfs_pool.c
man/man8/Makefile.am
man/man8/zfs_ids_to_path.8
tests/runfiles/common.run
tests/zfs-tests/include/commands.cfg
tests/zfs-tests/tests/functional/cli_root/Makefile.am
tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/Makefile.am
tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/cleanup.ksh
tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/setup.ksh
tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/zfs_ids_to_path_001_pos.ksh

= Merge Conflict
Job that hit the merge conflict: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/zfs/job/update/968/
```
10:23:28  CONFLICT (add/add): Merge conflict in cmd/zfs_ids_to_path/zfs_ids_to_path.c
10:23:28  Auto-merging cmd/Makefile.am
10:23:28  Automatic merge failed; fix conflicts and then commit the result.
10:23:28  git merge failed
10:23:28  Running: git merge --abort
10:23:28  Error: failed command 'merge_with_upstream'
10:23:28  Error: Failed merge with upstream for zfs
10:23:28  Error: buildpkg.sh failed.
```
= Diff
```diff
--- a/cmd/zfs_ids_to_path/zfs_ids_to_path.c
+++ b/cmd/zfs_ids_to_path/zfs_ids_to_path.c
@@ -35,7 +35,7 @@ libzfs_handle_t *g_zfs;
void
usage(int err)
{
-       fprintf(stderr, "Usage: ./os_id_to_name …
```

Fix merge conflict

---

include/sys/arc.h
module/zfs/arc.c
module/zfs/dmu_send.c

clean cherry-pick from master.
testing: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5207/

DLPX-69000 [Backport of DLPX-68999 to 6.0.3.0] Improve zfs send performance by bypassing the ARC

---

module/zfs/dmu_recv.c

This is essentially a follow-on to https://github.com/delphix/zfs/pull/159.  It is a clean cherry-pick of upstream's https://github.com/openzfs/zfs/pull/10320.
testing (in progress): http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5224/
If `receive_writer_thread()` gets an error from `receive_process_record()`,
it should be saved in `rwa->err` so that we will stop processing records,
and the main thread will notice that the receive has failed.
When an error is first encountered, this happens correctly.  However, if
there are more records to dequeue, the next time through the loop we
will reset `rwa->err` to zero, allowing us to try to process the
following record (2 after the failed record).  Depending on what types
of records remain, we may incorrectly …

Fix error handling in receive_writer_thread()

---

cmd/zpool/Makefile.am
configure.ac
copy-builtin
lib/libzutil/Makefile.am
module/.gitignore
module/Kbuild.in
module/Makefile.in
module/avl/Makefile.in
module/icp/Makefile.in
module/lua/Makefile.in
module/nvpair/Makefile.in
module/os/Makefile.in
module/os/linux/Makefile.in
module/os/linux/zfs/Makefile.in
module/spl/Makefile.in
module/unicode/Makefile.in
module/zcommon/Makefile.in
module/zfs/Makefile.in

The merge conflict was as follows:
```
108 <<<<<<< HEAD
109         kmoddir=$(DESTDIR)$(INSTALL_MOD_PATH)$(LINUX_MOD_DIR); \
110         debugdir=$(DESTDIR)$(INSTALL_MOD_PATH)$(LINUX_DEBUG_MOD_DIR); \
111         list='$(obj-m)'; for objdir in $$list; do \
112 =======
113         kmoddir=$(DESTDIR)$(INSTALL_MOD_PATH)/lib/modules/@LINUX_VERSION@
114         list='$(ZFS_MODULES)'; for objdir in $$list; do \
115 >>>>>>> zol/master                                                                                                                                                                                                            
116                 $(RM) -R $$kmoddir/$(INSTALL_MOD_DIR)/$$objdir; \
117                 $(RM) -fR $$debugdir/$(INSTALL_MOD_DIR)/$$objdir; \
118         done
``` …

Merge makefile

---

module/zfs/arc.c

Cap `zfs_arc_max` to 50% of all memory.
Note that this effectively reverts https://github.com/delphix/zfs/pull/98.
- ab-pre-push (esx): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3704/
- Manually checked on VM that `arc_c_max` was at 1/2 of all memory.

DLPX-70698 [Backport of DLPX-70697 to 6.0.3.0] Prevent zfs memory reaping logic from running by capping zfs_arc_max

---

module/zfs/arc.c

ZFS registers a memory hook (__arc_shrinker_func) which is supposed to allows the arc to shrink when the kernel experiences memory pressure. The logic, however, only adjusts the size of arc_c but does not wait for the eviction to happen. Since this function is called repeatedly, it results in a quick drop of the arc_c value all the way down to arc_c_min and since it doesn't wait for the actual eviction of the data from the arc it creates a situation where arc_size > arc_c. This condition causes all new allocations to stall in arc_get_data_impl:
```
/*
* If arc_size is currently overflowing, and has grown past our
* upper limit, we must be adding data faster than the evict
* thread can evict. Thus, to ensure we don't compound the
* problem by adding more data and forcing arc_size to grow …
```

DLPX-70719 [Backport of DLPX-70703 to 6.0.3.0] arc shrinking stalls allocations

---

cmd/arcstat/arcstat

Same diff as https://github.com/openzfs/zfs/pull/10494, except that the manpage doesn't exist on 5.3.
We'd like to get this in for enhanced observability.  There's basically zero risk, since this is only used by stats gathering / support bundles.

6.0.3.0: arcstat: add 'avail', fix 'free'

---

lib/libshare/nfs.c

`git zfs-make` (without `-P`) fails with the following warning:
```
make[3]: Entering directory '/export/home/delphix/zfs/lib/libshare'
CC       nfs.lo
nfs.c:239:1: error: no previous prototype for ‘nfs_exports_lock’ [-Werror=missing-prototypes]
nfs_exports_lock(void)
^~~~~~~~~~~~~~~~
nfs.c:293:1: error: no previous prototype for ‘nfs_exports_unlock’ [-Werror=missing-prototypes]
nfs_exports_unlock(void)
^~~~~~~~~~~~~~~~~~
Makefile:698: recipe for target 'nfs.lo' failed
```
It appears to have been introduced by ae7b167a98b482605 (Enable
-Wmissing-prototypes/-Wstrict-prototypes).  However, it doesn't cause a
failure in the automated builds, so this commit was auto-merged
successfully.  Presumably they work because they are nondebug and
therefore don't do this check.

Fix warning in libshare/nfs.c

---

module/zfs/arc.c

The process of evicting data from the ARC is referred to as "arc_adjust".
This commit changes the term to "arc_evict", which is more specific.
The new terminology will be extended in the forthcoming ARC changes.
No functional changes here, just code cleanup.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5336/
ZTS failures are same as [6.0/release](http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/run-zts/192/#showFailuresLink)
blackbox died in `dc snapshot`
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3759/
ui-precommit doesn't seem like it could be related to this change
upgrade test failed with `17:31:39  TestEnvironmentError: There is a problem with …

Adjust ARC terminology

---

include/os/linux/spl/sys/shrinker.h
include/os/linux/zfs/sys/trace_arc.h
include/sys/arc_impl.h
module/zfs/arc.c

The ARC shrinker callback `arc_shrinker_count/_scan()` is invoked by the
kernel's shrinker mechanism when the system is running low on free
pages.  This happens via 2 code paths:
1. "direct reclaim": The system is attempting to allocate a page, but we
are low on memory.  The ARC shrinker callback is invoked from the
page-allocation code path.
2. "indirect reclaim": kswapd notices that there aren't many free pages,
so it invokes the ARC shrinker callback.
In both cases, the kernel's shrinker code requests that the ARC shrinker
callback release some of its cache, and then it measures how many pages
were released.  However, it's measurement of released pages does not
include pages that are freed via `__free_pages()`, which is how the ARC
releases memory (via `abd_free_chunks()`).  Rather, …

Revise ARC shrinker algorithm

---

module/os/linux/zfs/vdev_disk.c

Backport change from upstream, hopefully decreasing the likelihood of hitting a race between device link deletion/creation and `vdev_device_open` - we've see this on customer systems as described here: https://jira.delphix.com/browse/DLPX-70675
Manually tested expanding devices. I don't yet have a case that reliably reproduces the race though, and since we can't simulate the exact conditions that customers hit this, it's hard to know if this will address all their problems..    
zfs-precommit: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5347/
John K confirmed that this only hit known test failures. 
ab-pre-push (passed): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3779/
We hit something …

ZTS: Fix zpool_reopen_001_pos

---

cmd/zfs/zfs_main.c
configure.ac
include/libzfs.h
include/libzfs_core.h
include/sys/dsl_dir.h
include/sys/fs/zfs.h
lib/libzfs/libzfs_dataset.c
lib/libzfs_core/libzfs_core.c
man/man8/zfs.8
module/os/linux/zfs/zfs_dir.c
module/os/linux/zfs/zfs_vfsops.c
module/zfs/dsl_dataset.c
module/zfs/dsl_destroy.c
module/zfs/dsl_dir.c
module/zfs/zfs_ioctl.c
tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
tests/zfs-tests/tests/functional/cli_root/Makefile.am
tests/zfs-tests/tests/functional/cli_root/zfs_wait/Makefile.am
tests/zfs-tests/tests/functional/cli_root/zfs_wait/cleanup.ksh
tests/zfs-tests/tests/functional/cli_root/zfs_wait/setup.ksh
tests/zfs-tests/tests/functional/cli_root/zfs_wait/zfs_wait.kshlib
tests/zfs-tests/tests/functional/cli_root/zfs_wait/zfs_wait_deleteq.ksh

DLPX-70838 [Backport of DLPX-61344 to 6.0.4.0] Need mechanism from ZFS to wait for the delete queue to drain
Cherry pick was not clean, most conflicts were with the BSD jails commit not being present. There was one conflict in zfs_dir.c , where master asserts that removing from the delete q returns 0 or ENOENT.
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5373/ ZTS failures are due to tests that are not passing in this release, not bugs in the backport.

Backport zfs wait

---

module/zfs/dsl_dir.c
tests/runfiles/linux.run

The original push contained a call to zfs_get_temporary_prop(), which
doesn't exist in 6.0/stage. Also, the new tests were not running
because they weren't added to the runfile.
Introduce a fix for the lack of zfs_get_temporary_prop (provided by
Paul) and add the tests to the runfile
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5383/
The failures in ZTS are all known and unrelated to this change.

Fixes for zfs wait backport

---

module/zfs/dsl_dataset.c
tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_clone_livelist.ksh

When a clone is promoted, its livelist is no longer accurate, so it is
discarded.  If the clone's origin is also a clone (i.e. we are promoting
a clone of a clone), then the origin's livelist is also no longer
accurate, so it should be discarded, but the code doesn't actually do
that.
Consider a pool with:
* Filesystem A
* Clone B, a clone of A
* Clone C, a clone of B
If we promote C, it discards C's livelist.  It should discard B's
livelist, but that is not happening.  The impact is that when B is
destroyed, we use the livelist to find the blocks to free, but the
livelist is no longer correct so we end up freeing blocks that are still
in use by C.  The incorrectly-freed blocks can be reallocated causing
checksum errors.  And when C is destroyed it can double-free the
incorrectly-freed …

DLPX-71272 [Backport of DLPX-71270 to 6.0.4.0] zfs promote does not delete livelist of origin

---

module/zfs/arc.c

This pulls in two parts missing pieces from upstream PR for [Revise ARC shrinker algorithm](https://github.com/openzfs/zfs/pull/10600) which allow the arc to notify the kernel shrinker that the arc is making progress and re-enables the kswapd.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3858/

DLPX-71340 [Backport of DLPX-71339 to 6.0.3.1] arc should handle indirect memory pressure

---

include/os/linux/spl/sys/kmem_cache.h
module/os/linux/spl/spl-kmem-cache.c
module/zfs/arc.c

http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5417/ (ZTS failures are known on 6.0)
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3852/ (failure is  DLPX-70498)

DLPX-71119 [Backport of DLPX-71118 to 6.0.4.0] Remove skc_reclaim, hdr_recl, kmem_cache shrinker

---

cmd/zfs/zfs_main.c
tests/zfs-tests/tests/functional/cli_root/zfs_set/canmount_002_pos.ksh

ab-pre-push with upgrade tests:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3879/

DLPX-71354 [Backport of DLPX-71313 to 6.0.4.0] Oracle VDB becomes inactive during deferred upgrades from 6.0.3.0

---

module/os/linux/zfs/arc_os.c
module/zfs/arc.c

Relevant commit:
e09b65e - DLPX-71406 [Backport of DLPX-71405 to 6.0.3.1] increase the
target for free system memory
Testing:
- Compiles
- zfs-precommit: http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5438/
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3903/

Forward-port arc_lowmem_init/arc_sys_free changes from 6.0/stage

---

cmd/zpool/zpool_main.c
include/libzfs.h
include/os/freebsd/spl/sys/mod_os.h
include/sys/fs/zfs.h
include/sys/vdev.h
include/sys/vdev_impl.h
lib/libzfs/libzfs_status.c
man/man5/zfs-module-parameters.5
man/man8/zpool.8
module/os/freebsd/zfs/sysctl_os.c
module/os/freebsd/zfs/vdev_file.c
module/os/freebsd/zfs/vdev_geom.c
module/os/linux/zfs/vdev_disk.c
module/os/linux/zfs/vdev_file.c
module/zfs/arc.c
module/zfs/spa.c
module/zfs/spa_config.c
module/zfs/vdev.c
module/zfs/vdev_indirect.c
module/zfs/vdev_mirror.c
module/zfs/vdev_missing.c
module/zfs/vdev_raidz.c
module/zfs/vdev_root.c

Merge Conflict Diff:
```
$ git diff
diff --cc include/sys/vdev.h
index 6207a47349,797065fdd0..0000000000
--- a/include/sys/vdev.h
+++ b/include/sys/vdev.h
@@@ -95,7 -94,7 +95,11 @@@ extern void vdev_rele(vdev_t *)
extern int vdev_metaslab_init(vdev_t *vd, uint64_t txg);
extern void vdev_metaslab_fini(vdev_t *vd);
extern void vdev_metaslab_set_size(vdev_t *);
++<<<<<<< HEAD
+extern void vdev_metaslab_group_create(vdev_t *vd);
++=======
+ extern void vdev_ashift_optimize(vdev_t *);
++>>>>>>> 6fe3498ca3406ffb10f729ab4f9cf63f10c74ede
extern void vdev_expand(vdev_t *vd, uint64_t txg);
extern void vdev_split(vdev_t *vd);
extern void vdev_deadman(vdev_t *vd, char *tag);
diff --cc module/zfs/vdev.c
index 3213ef0b88,1844a5653f..0000000000
--- a/module/zfs/vdev.c
+++ b/module/zfs/vdev.c
@@@ -5156,7 …
```

Fix Merge Conflict With Upstream

---

debian/tree/zfsutils-linux/usr/share/initramfs-tools/hooks/zdev

[This upstream merge PR](https://github.com/delphix/zfs/pull/213) has checkstyle failures that were unrelated to the changes in the commit: 
```
possible bashism in ./debian/tree/zfsutils-linux/usr/share/initramfs-tools/hooks/zdev line 57 (test -a/-o):
if [ -f '/etc/default/zfs' -a -r '/etc/default/zfs' ]
possible bashism in ./debian/tree/zfsutils-linux/usr/share/initramfs-tools/hooks/zdev line 63 (test -a/-o):
if [ -d '/etc/zfs' -a -r '/etc/zfs' ]
make: *** [checkbashisms] Error 1
Makefile:1470: recipe for target 'checkbashisms' failed 
```
This PR is to fix those bashisms.   The first version of this PR was garbage.  Thanks Prakash for waking me up.   What is being
complained about is using -a as the logical and.   I believe this can replaced with && if an additional sh square brace("[ …

Fix checkstyle bashisms

---

cmd/Makefile.am
cmd/zfs_file/Makefile.am
cmd/zfs_file/zfs_file.c
configure.ac
debian/zfsutils-linux.install
include/libzfs.h
include/sys/dmu.h
include/sys/dnode.h
include/sys/fs/zfs.h
lib/libzfs/libzfs_util.c
module/os/linux/zfs/zpl_file.c
module/zfs/dbuf.c
module/zfs/dmu.c
module/zfs/dnode.c
module/zfs/dnode_sync.c

We would like to determine how much of each VDB is accessed as part of the provisioning process (e.g. log replay), and then ongoing how much is further accessed over its lifetime. This will help us to understand how much of the VDB would need to be transmitted or cached.
To accomplish that, we add a range_tree to each dnode, which indicates which bytes of the file have been accessed. We update the range_tree when creating a dbuf for this dnode. Note that this information is lost when a dnode is destroyed (e.g. due to cache eviction), but in our use case that is unlikely to happen since there are few files and they are accessed frequently.
A new program, "zfs_file", is added to retrieve this information. It prints the percentage of the file that's been accessed, not exactly which bytes. …

DLPX-71837 track which blocks of a file have been accessed

---

.github/workflows/checkstyle.yaml

There is a github action which runs `make checkstyle`, which does
`make codecheck` and `make commitcheck`.  The `commitcheck` part results
in lots of checks that we don't actually want on the Delphix repo.
(e.g. commit line length, signed-off-by).
This commit changes the github action to instead run `make codecheck`,
which only checks the style of the code, which we do want to match the
upstream style so that we don't have diffs when upstreaming.
Applied this change to https://github.com/ahrens/zfs and then opened https://github.com/ahrens/zfs/pull/16.  Test results: https://github.com/ahrens/zfs/pull/16/checks?check_run_id=1162400005

do not check commit message

---

.github/workflows/checkstyle.yaml

clean backport of https://github.com/delphix/zfs/pull/223.
As shown in https://github.com/delphix/zfs/pull/221, PR's against 6.0/stage are not using the workflows in master.

6.0: do not check commit message

---

cmd/Makefile.am
cmd/zfs_file/Makefile.am
cmd/zfs_file/zfs_file.c
configure.ac
debian/zfsutils-linux.install
include/libzfs.h
include/sys/dmu.h
include/sys/dnode.h
include/sys/fs/zfs.h
lib/libzfs/libzfs_util.c
module/os/linux/zfs/zpl_file.c
module/zfs/dbuf.c
module/zfs/dmu.c
module/zfs/dnode.c
module/zfs/dnode_sync.c

clean cherry-pick of b159a3cbe1e246de60ec47ef3c19ded8c77ad378
http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5509/ (in progress)

DLPX-71838 [Backport of DLPX-71837 to 6.0.5.0] track which blocks of a file have been accessed

---

cmd/zed/zed.d/all-syslog.sh
cmd/zed/zed.d/zed.rc
tests/zfs-tests/tests/functional/events/events_001_pos.ksh
tests/zfs-tests/tests/functional/events/events_002_pos.ksh
tests/zfs-tests/tests/functional/events/events_common.kshlib

Clean cherry-pick of master commit (commit message below) into 6.0/stage (for 6.0.6).
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4262/
Also tested the VM image from above run to confirm new syslog changes were in effect.
========================================================
ZED will log zevents summaries to the syslog, however the log entries 
tend to drop event details that can be useful for diagnosis. This is 
especially true for ereport events, like io, checksum, and delay.
Update the all-syslog.sh script to log additional event information.
Add an optional config option, ZED_SYSLOG_DISPLAY_GUIDS, to zed.rc
for choosing GUIDs over names for pool and vdev.
Change the default ZED_SYSLOG_SUBCLASS_EXCLUDE to …

zed syslog entries drop important info

---

contrib/initramfs/hooks/zfsunlock.in

Clean cherry-pick of https://github.com/openzfs/zfs/pull/11162
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4301

DLPX-72754 [Backport of DLPX-72753 to 6.0.6.0] initramfs: zfsunlock hook breaks /usr/bin

---

Makefile.am
cmd/zpool_influxdb/Makefile.am
cmd/zpool_influxdb/README.md
cmd/zpool_influxdb/telegraf.d/exec_zpool_influxdb.conf
cmd/zpool_influxdb/telegraf.d/execd_zpool_influxdb.conf
contrib/dracut/90zfs/export-zfs.sh.in
contrib/dracut/90zfs/mount-zfs.sh.in
contrib/dracut/90zfs/parse-zfs.sh.in
contrib/dracut/90zfs/zfs-generator.sh.in
contrib/dracut/90zfs/zfs-lib.sh.in
contrib/dracut/90zfs/zfs-load-key.sh.in
contrib/dracut/90zfs/zfs-needshutdown.sh.in
debian/zfsutils-linux.install
etc/systemd/system/zfs-share.service.in
etc/systemd/system/zfs-volume-wait.service.in
etc/systemd/system/zfs-zed.service.in
rpm/generic/zfs.spec.in
scripts/Makefile.am
scripts/common.sh.in
scripts/zfs-tests.sh

Upstream has moved `zpool_influxdb` to a different directory, so we need to update our package files metadata to reflect this change. My manual change is in `debian/zfsutils-linux.install`.
Link to failure: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/zfs/job/pre-push/32/consoleFull.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4367/

Fix merge failure

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/checkstyle.yaml
tests/runfiles/common.run
tests/zfs-tests/tests/functional/cli_root/zfs_share/zfs_share_concurrent_shares.ksh

We made adjacent changes to checkstyle.yaml
```
diff --cc .github/workflows/checkstyle.yaml
index 924fe8c615,1707f5bb21..9db4492cd4
--- a/.github/workflows/checkstyle.yaml
+++ b/.github/workflows/checkstyle.yaml
@@@ -24,9 -24,10 +24,10 @@@ jobs
run: |
sh ./autogen.sh
./configure
+         make -j$(nproc)
-    - name: Checkstyle
+    - name: Codecheck
run: |
-        make checkstyle
+        make codecheck
- name: Lint
run: |
make lint
```
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4440/

Merge "Enable ABI checks for the checkstyle workflow"

---

module/zfs/metaslab.c

Since we have embedded slog metaslabs, the calculation in
metaslab_group_get_space() is no longer accurate, because it includes
all metaslabs (including the ZIL metaslab), not just the ones in the
requested group (which is of a particular class, e.g. normal, non-log
class).  Since the returned space is larger than expected, when
metaslab_class_fragmentation() divides by the class's space, we may get
a result >100.
testing:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4317/ (in progress)
manual testing with small, extremely-fragmented pool

assertion failed: fragmentation <= 100

---

include/sys/dmu.h
module/zfs/dsl_pool.c
module/zfs/spa.c

see [DLPX-73147](https://jira.delphix.com/browse/DLPX-73147)
I also plan to backport this to 6.0.6.0 and provide as a hotfix on 6.0.4.1 for [ESCL-3277](https://jira.delphix.com/browse/ESCL-3277)
copy-paste from JIRA below:
When migrating from 5.3 to 6.0, the refcount of SPA_FEATURE_BOOKMARK_V2 needs to be adjusted, due to the way we developed our changes years ago without coordinating with ZFS on Linux. This happens by calling sync_bookmark_featureflags_cb() on each dataset when we first import the pool on 6.0+. This function increments the refcount based on whether the bookmark is using new flags that require the V2 feature (HAS_FBN or redaction_obj). However, when the bookmark is deleted, it decrements the refcount based on the size of the ZAP entry (see …

DLPX-73147 panic: refcount!=0 in dsl_bookmark_destroy_sync_impl

---

module/zfs/dsl_bookmark.c

This is a clean cherry-pick of the upstream commit on master.
In the redaction list traversal code, there is a bug in the binary search
logic when looking for the resume point. Maxbufid can be decremented to -1,
causing us to read the last possible block of the object instead of the one we
wanted. This can cause incorrect resume behavior, or possibly even a hang in
some cases. In addition, when examining non-last blocks, we can treat the
block as being the same size as the last block, causing us to miss entries in
the redaction list when determining where to resume. Finally, we were ignoring
the case where the resume point was found in the buffer being searched, and
resuming from minbufid. All these issues have been corrected, and the code has
been significantly simplified to make future …

DLPX-72932 [Backport of DLPX-72918 to 6.0.6.0] kernel panic induced by SDD send

---

include/sys/dmu.h
module/zfs/dsl_pool.c
module/zfs/spa.c

backport for 6.0.6.0, same code as https://github.com/delphix/zfs/pull/238
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4493/
(verified that test failures occur in other builds as well, e.g. http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/blackbox-chained/6579/#showFailuresLink)

DLPX-73172 [Backport of DLPX-73147 to 6.0.6.0] panic: refcount!=0 in dsl_bookmark_destroy_sync_impl

---

rpm/generic/zfs-kmod.spec.in
rpm/redhat/zfs-kmod.spec.in

Errors Before this patch:
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/zfs-build-runner-uk3xLIor/BUILDROOT/zfs-kmod-2.0.0-rc1.x86_64
4425 error: Installed (but unpackaged) file(s) found:
4426
4427 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/avl/zavl.ko
4428 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/icp/icp.ko
4429 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/lua/zlua.ko
4430 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/nvpair/znvpair.ko
4431 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/spl/spl.ko
4432 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/unicode/zunicode.ko
4433 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/zcommon/zcommon.ko
4434 /usr/lib/debug/lib/modules/5.4.0-1031-azure/extra/zfs/zfs/zfs.ko …
```

Silence unpackaged_files RPM errors

---

cmd/zdb/zdb.c
cmd/ztest/ztest.c
include/sys/metaslab_impl.h
module/zfs/metaslab.c
module/zfs/spa.c
module/zfs/zio.c

There were merge conflicts in two files: 
cmd/ztest/ztest.c
module/zfs/spa_misc.c
For ztest.c delphix has rewritten the loop in the upstream code at 3137.  The change in the [upstream commit
](https://github.com/openzfs/zfs/commit/f8020c936356b887ab1e03eba1a723f9dfda6eea) was to change the initial value going into the loop.   So I pulled the value from the assignment at line 3136 up to line 3100. 
```
3100                 mg = rotor = spa_log_class(spa)->mc_rotor;
3101                 do {
3102                         if (mg == NULL) {
3103                                 /*
3104                                  * When we are in the middle of removing a
3105                                  * log device, the spa may still "have log
3106                                  * devices" (i.e. …
```

Merge Conflict

---

module/zfs/zio.c

clean backport of https://github.com/delphix/zfs/pull/233
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4535/ (hit https://jira.delphix.com/browse/TOOL-8365)
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4537/ (running)

DLPX-73394 [Backport of DLPX-73393 to 6.0.7.0] gang before embedded slog

---

etc/systemd/system/zfs-import-cache.service.in

We want to address the `open-iscsi` service start dependency with the zfs runtime. During boot, we want the `open-iscsi` service to run before we import the `domain0` pool via the `zfs-import-cache` service.
State the dependency in `zfs-import-cache.service` file
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4622/ 
confirming new dependency:
```
delphix@ip-10-110-237-170:~$ systemctl list-dependencies --before open-iscsi.service
open-iscsi.service
● ├─zfs-import-cache.service
● ├─remote-fs-pre.target
● │ ├─remote-fs.target
● │ │ ├─kexec-load.service
● │ │ ├─rng-tools.service
● │ │ ├─rtslib-fb-targetctl.service
● │ │ └─systemd-user-sessions.service
● │ └─shutdown.target
● └─shutdown.target
```
also
- Confirmed that …

DLPX-73192 Establish systemd service dependencies for iSCSI

---

cmd/zdb/zdb.c
cmd/ztest/ztest.c
include/sys/dmu.h
include/sys/spa.h
include/sys/spa_impl.h
include/sys/vdev.h
include/sys/vdev_impl.h
man/man5/zfs-module-parameters.5
module/zfs/metaslab.c
module/zfs/spa.c
module/zfs/spa_misc.c
module/zfs/vdev.c
module/zfs/vdev_removal.c
module/zfs/zfs_log.c
module/zfs/zio.c
module/zfs/zvol.c
tests/zfs-tests/tests/functional/alloc_class/alloc_class_013_pos.ksh
tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_014_neg.ksh
tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_015_neg.ksh

This PR merges the upstream commit for "Set aside a metaslab for ZIL blocks".  It updates the Delphix embedded slog implementation to match that of the upstream PR: https://github.com/openzfs/zfs/pull/11389.  This resolves the largest code difference that we have against upstream, and the source of several recent merge conflicts.
The change in behavior for the Delphix Engine is minimal: single-sector normal-class allocations (typically gang blocks) can no longer fall back to the embedded ZIL metaslab.  In practice this case would never be hit.
There are several changes in the way that it's been implemented:
1. embedded metaslabs are part of the new spa_embedded_log_class (not spa_log_class)
2. embedded metaslabs exist regardless of presence of a log device (dedicated slog)
3. embedded …

embedded slog updates

---

include/sys/metaslab.h
man/man5/zfs-module-parameters.5
module/zfs/metaslab.c
module/zfs/zio.c

clean backport of https://github.com/openzfs/zfs/pull/11327
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4548/

DLPX-73281 [Backport of DLPX-73280 to 6.0.7.0] Only examine best metaslabs on each vdev

---

cmd/zdb/zdb.c
include/sys/dsl_bookmark.h
module/zfs/dmu_redact.c
module/zfs/dmu_send.c
module/zfs/dsl_bookmark.c

Signed-off-by: Paul Dagnelie <pcd@delphix.com>
We want to integrate these diagnostics on master as well, in case customers encountering this issue want to upgrade to 6.0 before we can resolve the issue. We don't need to backport this to any releases that we don't want the logic to end up in.  This is a relatively clean cherry-pick of the changes from 5.3.9.0 onto Linux.

DLPX-74369 add diagnostics to root-cause possible bookmark corruption

---

cmd/zdb/zdb.c
include/sys/dsl_bookmark.h
module/zfs/dmu_redact.c
module/zfs/dmu_send.c
module/zfs/dsl_bookmark.c

Clean cherry-pick of https://github.com/delphix/zfs/pull/257 onto 6.0/stage
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5014/ (zloop failure appears unrelated)

DLPX-74370 [Backport of DLPX-74369 to 6.0.8.0] add diagnostics to root-cause possible bookmark corruption

---

module/zfs/dmu_redact.c
module/zfs/dsl_bookmark.c

http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5078/ (in progress)

DLPX-75381 Diagnostics collection related to bookmark corruption contains junk values 

---

module/zfs/dmu_redact.c
module/zfs/dsl_bookmark.c

Clean cherry-pick of https://github.com/delphix/zfs/pull/262 to 6.0/release for 6.0.8.0

DLPX-75382 [Backport of DLPX-75381 to 6.0.8.0] Diagnostics collection related to bookmark corruption contains junk values

---

cmd/zpool/zpool_vdev.c
include/sys/fs/zfs.h
module/zcommon/zpool_prop.c
tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg

This PR currently fails to create an objstore pool when the kernel fails to allocate a vdev because there are no vdev ops for the objstore type of vdev. However, the userland components appear to be working correctly:
```
delphix@pd-test:~$ sudo zpool create -o object-endpoint=foo  test2 s3 baz
No credentials location provided for objstore vdev baz
delphix@pd-test:~$ sudo zpool create -o object-credentials-location=bar test2 s3 baz
No endpoint provided for objstore vdev baz
delphix@pd-test:~$ sudo zpool create -o object-endpoint=foo -o object-credentials-location=bar test2 s3
invalid vdev specification: 's3' requires a parameter
delphix@pd-test:~$ sudo zpool create -o object-endpoint=foo -o object-credentials-location=bar test2 s3 baz
cannot create 'test2': invalid argument for this pool …
```

Implement creation of objstore pools in userland

---

cmd/zfs_object_agent/Cargo.lock

Ran `cargo update` to switch to new versions of dependencies.  In
particular, this gets us the changes to rust-libzfs required to build
with the older version of rustc that will be installed on the appliance.
See also:
https://github.com/ahrens/rust-libzfs/pull/1
https://github.com/delphix/appliance-build/pull/544

update dependencies for libzfs changes

---

cmd/zfs_object_agent/src/server.rs

```
root@mj-agent:/export/home/delphix/zfs/cmd/zfs_object_agent# cat /etc/zpool_credentials
<access-id>:<secret-key>
root@mj-agent:/export/home/delphix/zfs/cmd/zfs_object_agent# zpool create -o object-endpoint=https://s3-us-west-2.amazonaws.com  -o object-region=us-west-2  -o object-credentials-location=file:///etc/zpool_credentials  domain0 s3 cloudburst-data-2
root@mj-agent:/export/home/delphix/zfs/cmd/zfs_object_agent#
```

Change credentials file format to just be "<access-key-id>:<secret-access-key>"

---

etc/systemd/system/zfs-zed.service.in

We are still encountering ZED crashes in automated testing from master. While we wait for upstream to resolve the issue (PR-11965), this PR will deploy a simple work-around.
Change the `zfs-zed` service so that it launches with jobs capped to 1 so that it is not possible to encounter the race that leads to ZED crashing.  This effectively has the same behavior as before async zedlet execution was introduced.
ab-pre-push:   http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5147/
Confirmed from image built from ab-pre-push result that ZED is running with -j 1
```
delphix@ip-10-110-246-215:~$ ps aux | grep zed
root      1836  0.0  0.0 201064  3196 ?        Ssl  22:37   0:00 /usr/sbin/zed -F -j 1
```

DLPX-75168 zed core detected during automated tests

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/Cargo.toml
cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs

Add a small cache of recently read objects.
Make background freeing stop when we reach the low water mark (0.5% of blocks are pending frees).  Process objects with pending frees in order of how many pending frees they have.

object cache; freeing low water

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/Makefile.am
cmd/zfs_object_agent/client/Cargo.toml
cmd/zfs_object_agent/client/src/client.rs
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/server/Cargo.toml
cmd/zfs_object_agent/server/src/main.rs
cmd/zfs_object_agent/src/lib.rs
cmd/zfs_object_agent/src/server.rs

I pulled out the client and server code into bin packages and left the common code in the root crate.
The agent binary continues to be `/sbin/zfs_object_agent`. The client is `/sbin/zoa_test`.

Split into client, server and common code

---

cmd/zfs_object_agent/client/Cargo.toml
cmd/zfs_object_agent/server/Cargo.toml
cmd/zfs_object_agent/src/object_access.rs
debian/zfsutils-linux.install
etc/systemd/system/Makefile.am
etc/systemd/system/zfs-object-agent.service.in
rpm/generic/zfs.spec.in

When started as a service the agent would find the env variable USER unset and panic (even when the file /etc/machine-id was present). Fixed it to look at USER only if AWS_PREFIX is unset and machine-id is unavailable.
```
delphix@mj-agent:~$ systemctl list-unit-files | grep zfs
zfs-import-cache.service               enabled        
zfs-import-scan.service                disabled       
zfs-import.service                     masked         
zfs-mount.service                      enabled        
zfs-object-agent.service               disabled       <-----------
zfs-share.service                      enabled        
zfs-volume-wait.service                enabled        
zfs-zed.service                        enabled        
zfs-import.target                      enabled …
```

systemd service for zfs-object-agent 

---

module/zfs/spa.c
module/zfs/vdev_label.c

As discussed in the team meeting, we fix this issue by not attempting to redo the stop operations if they already occurred in spa_export (as determined by the spa_final_txg being set)

Try to fix existing export bug masked by no-op

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/Cargo.toml
cmd/zfs_object_agent/client/Cargo.toml
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/server/Cargo.toml
cmd/zfs_object_agent/server/src/main.rs
cmd/zfs_object_agent/src/lib.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/object_block_map.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs
cmd/zpool/zpool_main.c
lib/libzutil/zutil_import.c
module/os/linux/zfs/vdev_object_store.c
module/zfs/spa.c

- add new ObjectBasedLog to track object sizes
- use new accounting to consolidate small adjacent objects when freeing
- improve some existing space accounting
- object-block mapping can be addressed by either object or block (because it's sorted by both)
- reduce dependencies in cargo files
- fix cstyle errors

object consolidation

---

cmd/zfs/zfs_main.c
lib/libzfs/libzfs_dataset.c
lib/libzfs/libzfs_diff.c
lib/libzfs/libzfs_mount.c
lib/libzfs/libzfs_sendrecv.c

Revert "zfs get: don't lookup mount options when using "-s local""
This reverts commit e4288a8397bb1f9df763c08bf93260062da8173a.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5182/ (running)

DLPX-75537 libzfs API change breaks Oracle SnapSync

---

cmd/zfs_object_agent/Cargo.toml
cmd/zfs_object_agent/src/base_types.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs

- rearrange the background freeing code
- use a closure/callback to complete freeing in syncing context (txg_end)
- improvements to space accounting
- minor cleanup elsewhere

use a closure to complete freeing in syncing context

---

cmd/zed/zed_exec.c

This is for **DLPX-75168** (zed core detected during automated tests)
The first attempt to close a race introduced with the async zedlet execution feature (PR-11965, commit f9bece92e24b) did not completely eliminate the race and we are occasionally encountering zed cores in automated testing.  The upstream contributor, Ahelenia, was able to finally reproduce the crash we observed and offer a revised fix that eliminates the race.
```
zed: protect against wait4()/fork() races to the global PID table
This can be very easily triggered by adding a sleep(1) before
the wait4() on a PID-starved system: the reaper thread would wait
for a child before its entry appeared, letting old entries accumulate:
Invoking "all-debug.sh" eid=3021 pid=391
Finished "(null)" eid=0 pid=391 time=0.002432s exit=0 …
```

zed: protect against wait4()/fork() races to the global PID table

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/Cargo.toml
cmd/zfs_object_agent/client/Cargo.toml
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/object_block_map.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs

- use rusoto for most S3 calls
- add ObjectAccess struct to encapsulate data needed for S3 calls (rusoto or rust-s3)
- add jitter to S3 retryer
- creds/endpoint strings procesing moved from Server to ObjectAccess
- delete multiple objects with one S3 call
- ObjectBasedLog track num_entries
- target DataObject size is now 1MB (before was 100 blocks)
- target ObjectBasedLog size is now 100,000 entries (before was 1000 entries)
- pending frees high/low-water changed to 10%/9%
- DataObject tracks min/max blockID and min/max txg
- simplified members tracking PendingObject
- improved object-consolidation logic; throttle put/get requests

rusoto & more

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/client/src/client.rs
cmd/ztest/ztest.c
include/sys/Makefile.am
include/sys/sock.h
lib/libzpool/Makefile.am
module/os/linux/zfs/Makefile.in
module/os/linux/zfs/sock.c
module/os/linux/zfs/vdev_object_store.c
module/zfs/metaslab.c
module/zfs/spa.c
module/zfs/vdev.c
module/zfs/vdev_label.c
module/zfs/zio.c

With these changes, ztest runs on object-store based zpools. I was able to get it to run for 8 hours after which it crashed due to a problem that looks unrelated to this change.
```
root@mj-dose:/export/home/delphix/zfs/cmd/ztest# date; ./ztest -O https://s3-us-west-2.amazonaws.com -A us-west-2 -b cloudburst-data-2 -z file:///etc/zfs/zpool_credentials -T 30 -VV; date
Tue May 11 07:35:34 UTC 2021
7 datasets, 23 threads, object-store https://s3-us-west-2.amazonaws.com, 30 seconds...
Skipping executing zdb.
error == 0 (0x1c == 0)
ASSERT at ../../module/zfs/zio.c:3509:zio_object_allocate_and_issue()/export/home/delphix/zfs/cmd/ztest/.libs/ztest(+0x9eb3)[0x55ed58a48eb3]
<snip>
child died with signal 6
Tue May 11 15:40:57 UTC 2021
root@mj-dose:/export/home/delphix/zfs/cmd/ztest# 
```
```
#2 …
```

ztest on an object store based zpool

---

cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/pool.rs

- only iterate over (GetObject) chunks whose PutObject command has completed
- condense the object_size_log when it has lots of small chunks (objects)

condense object_size_log

---

cmd/zfs_object_agent/src/pool.rs

AWS's guidance on how exactly this works, and whether you need to do anything beyond just "having separate prefixes" to get improved performance, is *extremely* unclear. From what I can tell, the simple version of the design is that the prefix of an object (everything up to the last /) is used as a key in a hash table to determine what node(s) to go talk to.
Now, does this mean you could just have every object end with "/data" and then each is its own prefix, giving you the maximum theoretical requests per object? Maybe, but my guess is no. My guess is that if expanding a particular "directory" (thing between two /s) would make the hash table larger than a certain size, they don't use that as part of the partitioning scheme. Maybe that size is linked to the number of objects in the …

Use prefixes for data objects to increase parallelism

---

cmd/zdb/zdb.c
cmd/ztest/ztest.c
lib/libzutil/os/linux/zutil_import_os.c

This change enables zdb to inspect an object-store based zpool that is exported/not in a cachefile.
I also enables ztest to run zdb.
Caveat: If there are multiple pools with the same name, zdb struggles as it does not yet know how to specify the pool ID. For example, when there are multiple "ztest" pools in the bucket, zdb fails.
```
root@mj-dose:/export/home/delphix/zfs/cmd/zdb# ./zdb -e -a https://s3-us-west-2.amazonaws.com -g us-west-2 -B cloudburst-data-2 -f file:///etc/zfs/zpool_credentials ztest | more
Configuration for import:
vdev_children: 1
version: 5000
pool_guid: 9962155298875414703
name: 'ztest'
state: 0
vdev_tree:
type: 'root'
id: 0
guid: 9962155298875414703
children[0]:
type: 'object_store'
id: 0
guid: 17635164701915965417
object-credentials-location: …
```

zdb support for object-store based zpools

---

cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs

I think this should make the "flush writes" command work correctly with out-of-order write processing.

improved flush command

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/Cargo.toml
cmd/zfs_object_agent/server/src/main.rs
cmd/zfs_object_agent/src/base_types.rs
cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs
module/os/linux/zfs/vdev_object_store.c

- pad out numbers in keys to be 20 decimal digits
- change all but data objects to be JSON-encoded
- add "resume txg" and "resume complete" commands to get agent back into the same state as before we crashed.
- add just enough error handling for `zpool import` to not explode on old-format pools.  We can consider revising this once we have proper versioning of the on-disk format
- minor tweaks to log formatting
After running `zpool import` we see several error messages like these in the log.
example error message when object does not exist (due to padding `0`s):
```
[2021-05-24 04:10:39.248][::server][DEBUG] prefix: zfs/7889576177877413145/
[2021-05-24 04:10:39.248][::object_access][DEBUG] get zfs/07889576177877413145/super: begin
[2021-05-24 …
```

Agent recovery

---

etc/systemd/system/zfs-zed.service.in

As a work-around to avoid ZED crashes, we had forced the simultaneous ZED jobs to 1.
Now that there is a fix that solves the crashes we can revert this work-around.
This reverts commit e2035aa1c11ff2b0a8d4fe375ad7030c8475048c.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5348/

Revert zed workaround since zed crashes are now fixed (#284)"

---

cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/object_block_map.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs
module/os/linux/zfs/vdev_object_store.c

- restructure get_object() to directly pass data to readers that come in while a read is in progress
- list_objects(): remove delimiter parameter (it's always `"/"`)
- add helper functions collect_objects() and collect_prefixes() (based on list_objects()), which simplifies callers
- add DataObjectPhys::get_from_key() which allows removal of string processing from get_recovered_objects()
- restructure iteration code in resume_complete() to decrease mutability and `if` statements
- undo uncommitted object consolidation, add assertions to ensure that we can delete to-be-emptied objects without reading them
- begin_txg needs to wait for READY

agent code cleanup

---

etc/systemd/system/zfs-object-agent.service.in
lib/libzutil/os/linux/zutil_import_os.c
module/os/linux/zfs/vdev_object_store.c

The check "vos_sock == NULL" should have been "vos_sock == INVALID_SOCKET".
zdb blows up because of this.
```
delphix@ip-10-110-202-140:~$ sudo zdb ztest
vos->vos_sock == NULL (0xffffffffffffffff == 0x0)
ASSERT at ../../module/os/linux/zfs/vdev_object_store.c:844:vdev_object_store_socket_open()Aborted
delphix@ip-10-110-202-140:~$ 
```
Tested the fix to validate that zdb is able to access the object store with the fix.
```
delphix@mj-zdb:~$ sudo zpool create -o object-endpoint=https://s3-us-west-2.amazonaws.com  -o object-region=us-west-2  -o object-credentials-location=file:///etc/zfs/zpool_credentials  ztest25 s3 cloudburst-data-2
delphix@mj-zdb:~$ sudo zpool export ztest25
delphix@mj-zdb:~$ sudo zdb -bcc -G -d -Y -e -y  -a https://s3-us-west-2.amazonaws.com -g us-west-2 -B …
```

Fix for assertion failure: vos->vos_sock == NULL (0xffffffffffffffff == 0x0)

---

cmd/zfs_object_agent/src/object_block_map.rs
cmd/zfs_object_agent/src/pool.rs

Use the "interior mutability" design pattern to move the locking into
the ObjectBlockMap itself, rather than its consumer, Pool.

clean up ObjectBlockMap

---

cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs

- flush all logs concurrently
- rename pool:PoolSharedState -> shared_state
- delete_objects() can take a slice
- Don't need Arc with Bytes
- Change locking strategy: `syncing_state: std::sync::Mutex<Option<PoolSyncingState>>,` and `with_syncing_state()` helper function to obtain lock & run closure
This lets us serialize the initial processing of write_block(), which lets us remove the race condition at the beginning of `resume_complete()` (and sleep(1s) to work around it)
- fix a bug in `check_pending_flushes()`

update agent PoolSyncingState locking strategy

---

cmd/ztest/ztest.c

After skipping a bunch of tests, ztest is able to run tests and run zdb on zpools successfully.
Well, almost... There is still an ENOSPC error that we see in metaslab_alloc() in zio_object_allocate_and_issue(). But there is enough progress here to commit.
Since we have a shared storage (s3), there are usually multiple pools with the name "ztest" left around. For ztest to call zdb reliably, it needs to specify the guid instead of the pool name. So, we stash away the guid in `zs_guid` which was unused AFAICT, before this change.

ztest improvements

---

etc/systemd/system/zfs-object-agent.service.in

- Make the agent restart `Restart=always`.
- More verbose logging for the agent with `-vv`
Tested that the agent restarts as expected and we get verbose logs.

DOSE-257 Killing zfs-object-agent service doesn't always restart the service

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/client/Cargo.toml
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/src/object_access.rs

`zoa_test delete` fails with the oom-killer killing it when there are many (over 15K does the trick). `zoa_test list` also has difficulties with listing many objects.
The problem is that we fetch all the objects in one fell swoop and fire off futures all in one go. What this change does is two things. It processes the fetched list in batches. It also does a paged fetch (`bucket.list_page()` as opposed to `bucket.list()`).
Also added is the ability to list|delete objects older than a specified number of days. This can be used to cleanup older objects that are no longer in use. We have about 3.5 million objects older than 10 days that can potentially be cleaned up.
```
root@mj-zdb-2:~# export AWS_PREFIX=123456789
root@mj-zdb-2:~# /export/home/delphix/zfs/cmd/zfs_object_agent/target/debug/zoa …
```

More robust zoa_test list|delete

---

cmd/zfs_object_agent/Makefile.am
cmd/zfs_object_agent/scripts/zoa_chaos_monkey
debian/zfsutils-linux.install
etc/systemd/system/Makefile.am
etc/systemd/system/zoa-chaos-monkey.service.in
rpm/generic/zfs.spec.in

The Chaos Monkey service kills the ZFS Object Agent process periodically and may be use to test agent recovery.
It sleeps for a random number of seconds, between 60 and 300. On waking up, it sends a kill signal to the zfs_object_agent process and then goes back to sleep again.
How aggressively the process is killed may be tuned by changing the amount of time the service waits before killing the agent. This is done with a a service override (see below).
Testing:
```
delphix@mj-chaos-1:~$ sudo systemctl start zfs-object-agent.service
delphix@mj-chaos-1:~$ sudo systemctl start zoa-chaos-monkey.service
delphix@mj-chaos-1:~$ sudo systemctl status zfs-object-agent.service
● zfs-object-agent.service - ZFS object agent
Loaded: loaded (/lib/systemd/system/zfs-object-agent.service; disabled; vendor …
```

ZFS Object Agent chaos monkey service

---

include/sys/vdev_impl.h
module/os/linux/zfs/vdev_object_store.c
module/zfs/spa.c
module/zfs/vdev_label.c
module/zfs/zio_inject.c

This PR will replay the `end_txg` request if we need to resume at the end of spa_sync. In addition, it changes our serial waiters to ensure we wake up the correct serial waiters when we are resuming.
This also add `zinject` points to force a agent failure at pre-determined points. The points are defined to force an agent crash before we connect, or after connection. Here's an example:
```
root@gwilson-zfs:~# zinject -p agent_request_zio test 1
Added handler 2 with the following properties:
pool: test
panic function: agent_request_zio
```
This will force the agent to restart just prior to an I/O being issued on the socket:
```
[2021-05-28 18:59:25.337][::pool][DEBUG] TXG(11): writing ObjectID(20): blocks=7 bytes=6656 min=BlockID(105)
[2021-05-28 18:59:25.337][::pool][DEBUG] ObjectID(20): …
```

fix reissuing issues

---

cmd/zfs_object_agent/scripts/zoa_chaos_monkey
etc/systemd/system/zoa-chaos-monkey.service.in

Change chaos-monkey's default kill delay to 0-300 seconds.
Testing:
```
delphix@mj-chaos-1:~$ sudo systemctl start zfs-object-agent.service
delphix@mj-chaos-1:~$ sudo systemctl start zoa-chaos-monkey.service
delphix@mj-chaos-1:~$ sudo journalctl -u zoa-chaos-monkey.service -f
-- Logs begin at Sat 2021-06-05 00:17:22 UTC. --
Jun 10 18:55:46 mj-chaos-1.dcol2 systemd[1]: Started ZFS Object Agent Chaos Monkey.
Jun 10 18:55:46 mj-chaos-1.dcol2 zoa_chaos_monkey[7792]: Max kill delay: 300
Jun 10 18:55:46 mj-chaos-1.dcol2 zoa_chaos_monkey[7792]: Min kill delay: 0
Jun 10 18:55:46 mj-chaos-1.dcol2 zoa_chaos_monkey[7792]: Sleeping for 274 seconds.
```

Change chaos-monkey's kill delay to [0-300] seconds

---

cmd/zfs_object_agent/Cargo.lock
cmd/zfs_object_agent/Cargo.toml
cmd/zfs_object_agent/client/Cargo.toml
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/server.rs
etc/systemd/system/zfs-object-agent.service.in

Update: This change is now ready for review.
----
Matt, I am posting this PR is for discussing ZOA's credential management with you.
It looks like rusoto has the ability to source AWS access credentials from multiple sources, including IAM EC2 instance profile.
See: https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md
I wrote a simple test to demonstrate this. I ran the test on my VM based on the new `OBJECT` type that devops is building.
```
delphix@ip-10-110-137-138:~/zfs/cmd/zfs_object_agent$ unset AWS_ACCESS_KEY_ID
delphix@ip-10-110-137-138:~/zfs/cmd/zfs_object_agent$ unset AWS_SECRET_ACCESS_KEY
delphix@ip-10-110-137-138:~/zfs/cmd/zfs_object_agent$ target/debug/zoa_test rusoto_role
bucket: Bucket { name: "dcoa-gparton-manoj-object-storage", region: UsWest2, credentials: …
```

Make Rusoto source AWS access credentials via IAM EC2 instance profile

---

cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs
include/sys/Makefile.am
include/sys/vdev_impl.h
include/sys/vdev_object_store.h
module/os/linux/zfs/vdev_object_store.c
module/zfs/metaslab.c
module/zfs/spa.c
module/zfs/vdev_label.c
module/zfs/zio.c
module/zfs/zio_inject.c

Add support for zpool `allocated` and `freeing` properties.
Rather than an explicit "get props" command to the agent, I return the stats each TXG, as part of the "txg end done" response.  So this will only update once per txg, but I think that should be fine.
Let me know if there are other existing properties that should have a meaning for object store.  (Suggestions of new properties also welcome but I wanted to hook up existing ones first.)
```
root@mahrens-agent:~# zpool list -v test
NAME                  SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
test                  512P  34.5G   512P        -         -     0%     0%  1.00x    ONLINE  -
cloudburst-data-2   512P  34.5G   512P        -         -     0%  0.00%      -    ONLINE
root@mahrens-agent:~# …
```

zpool properties

---

cmd/zfs_object_agent/src/object_block_map.rs
cmd/zfs_object_agent/src/pool.rs

@don-brady hit a bug where the `unwrap()` in  `ObjectBlockMap::object_to_next_block()` failed.  The problem occurs when we call this function on the last object in the pool.  In this case we try to find its "next block" by getting the "first block" of the next object.  However, since this is the last object, there is no "next object".
The solution is for the ObjectBlockMap to keep track of the pool-wide "next block", which is the "next block" of the last object.  While implementing this, we realized that the code could be cleaned up by having ObjectBlockMap encapsulate more of the functionality related to the on-disk representation (the `ObjectBasedLog<StorageObjectLogEntry>`).  More cleanup of this interface is forthcoming.

fix bug in ObjectBlockMap::object_to_next_block

---

cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/pool.rs

When running a workload of writing/freeing to the object store pool, @don-brady noticed a lot of messages like this in the agent's log:
`[2021-07-01 03:06:50.156][::object_access][DEBUG] get zfs/11689269492085668192/PendingFreesLog/00000000000000000022/00000000000000002364 returned: HttpDispatch(HttpDispatchError { message: "Error during dispatch: error trying to connect: tcp open error: Too many open files (os error 24)" }); retrying in 80ms`
Turns out that the changes in https://github.com/delphix/zfs/pull/350 accidentally changed the behavior such that buffered streams were no longer effectively buffered.  This is especially impactful in `ObjectBasedLog::iter_impl()`.

async move

---

cmd/zfs_object_agent/src/block_allocator.rs
cmd/zfs_object_agent/src/block_based_log.rs
cmd/zfs_object_agent/src/index.rs
cmd/zfs_object_agent/src/lib.rs
cmd/zfs_object_agent/src/space_map.rs
cmd/zfs_object_agent/src/zettacache.rs

Based on discussion with @sdimitro, made some changes to the interfaces within the zettacache:
- combine `.get_phys()` and `.flush()` calls into one API (`.flush()` which returns the new "phys")
- move "index" data structures to their own file
Note: the idea of combining .get_phys() into .flush() applies to the object management part of the agent as well.  It's a little more complicated to do there but I'll work on that next.
I'm also considering making the .flush() API a Rust `trait`, which would let us enforce some things about that interface but it makes the code slightly harder to navigate, so I'm putting that off until I find a more clear benefit (e.g. we want to be able to "register" a bunch of "flushable" objects and then call all of them with a `for` loop, rather than the current …

clean up zettacache interfaces

---

module/zfs/metaslab.c

Subtract out the space used by object storage vdev when destroying its (single) metaslab.

DOSE-465 fix vs_alloc panic on export

---

cmd/zfs_object_agent/client/src/client.rs
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/src/base_types.rs
cmd/zfs_object_agent/src/block_based_log.rs
cmd/zfs_object_agent/src/index.rs
cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/object_based_log.rs
cmd/zfs_object_agent/src/object_block_map.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs
cmd/zfs_object_agent/src/space_map.rs
cmd/zfs_object_agent/src/zettacache.rs

This PR fixes all the issues reported by `cargo clippy`, which is the rust linter. Most of the changes are to comply with the Rust naming conventions (acronyms and initialisms should only capitalize the first letter), though one is left as is with the lint warning disabled for comparison. If people prefer that approach, the others can be changed to do the same.  The contentful changes are to remove some redundant clones, removing a closure by using the function as a first-class entity, and changing the Mutex<usize> for the outstanding write count to an AtomicUsize.

Make cargo clippy clean

---

include/sys/zthr.h
module/zfs/arc.c
module/zfs/zthr.c

Run arc_evict thread at higher priority, nice=0, to give it more CPU time
which can improve performance for workload with high ARC evict activities.
On mixed read/write and sequential read workloads, I've seen between
10-40% better performance.
Extending zthr_create_timer() to take a new priority_t argument and
arc_evict_zthr is created with defclsyspri (nice=0) priority value rather than
the current minimum priority (nice=19).
Observed performance gains with nice=0 and nice=-20 comparing to current nice=19
VM config: 16 vCPU, 32 GB RAM, 4 x 200 GB disks
Workload: 32 threads x 1M sequential reads
minclsyspri (nice 19) current value: 1301 IOPS, 1365 MB/s, 37-45% idle
defclsyspri (nice 0): 1860 IOPS, 1951 MB/s, 22-25% idle
maxclsyspri (nice -20): 1929 IOPS, 2023 MB/s, 20-22% idle …

[Hotfix for: ESCL-3554] High NFS read latency on 6.0.6.1

---

cmd/Makefile.am
cmd/zfs_object_agent/.gitignore
cmd/zfs_object_agent/Makefile.am
cmd/zfs_object_agent/scripts/Makefile.am
configure.ac
rpm/generic/zfs.spec.in

With this change, automated builds succeed. This changes fixes the following build failures:
```
Making all in zfs_object_agent
make[5]: *** No rule to make target 'scripts/zoa_chaos_monkey', needed by 'all-am'.  Stop.
```
```
Making all in zfs_object_agent
error: could not find `Cargo.toml` in `/tmp/zfs-build-delphix-FQxEFmaA/BUILD/zfs-2.1.99/cmd/zfs_object_agent` or any parent directory
error: could not find `Cargo.toml` in `/tmp/zfs-build-delphix-FQxEFmaA/BUILD/zfs-2.1.99/cmd/zfs_object_agent` or any parent directory
Makefile:945: recipe for target 'zoa_test' failed
make[5]: *** [zoa_test] Error 101
```
```
Installed (but unpackaged) file(s) found:
/usr/bin/zoa_chaos_monkey
Makefile:1651: recipe for target 'rpm-common' failed
make[1]: *** [rpm-common] Error 1
```
```
make codecheck …
```

Fix build failures

---

cmd/zfs_object_agent/src/server.rs
include/sys/vdev_impl.h
include/sys/zio.h
module/os/linux/zfs/vdev_object_store.c
module/zfs/vdev_queue.c
module/zfs/zio.c

This PR allows an unlimited queue (unless we run out of memory) of outstanding I/Os. It repurposes the vdev_queue's vq_active_tree which is not used for object storage to store the pending I/Os.
With this change we are able to get ~450MB/s of sequential writes and ~140MB/s of sequential reads.

DOSE-283 allow unlimited I/O requests

---

cmd/zdb/zdb.c
cmd/zfs_object_agent/client/src/client.rs
cmd/zfs_object_agent/client/src/main.rs
cmd/zfs_object_agent/src/heartbeat.rs
cmd/zfs_object_agent/src/object_access.rs
cmd/zfs_object_agent/src/pool.rs
cmd/zfs_object_agent/src/server.rs
cmd/zpool/zpool_main.c
cmd/zpool/zpool_vdev.c
cmd/ztest/ztest.c
include/libzfs.h
include/libzutil.h
include/sys/fs/zfs.h
lib/libzfs/libzfs_crypto.c
lib/libzfs/libzfs_impl.h
lib/libzfs/libzfs_pool.c
lib/libzutil/os/linux/zutil_import_os.c
lib/libzutil/zutil_import.c
module/os/linux/zfs/vdev_object_store.c
module/zcommon/zpool_prop.c
module/zfs/spa.c
tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg

The zfs-object-agent now deals with credentials the AWS way (via ~/.aws/credentials and ~/.aws/config). The ZFS kernel module no longer needs to concern itself with reading the credentials file. This change removes the `object-credentials-location` parameter.
To support using different credentials for different zpools, an optional `object-credentials-profile` parameter is being added. If it is not specified, a "default" profile is assumed.
Testing:
Setup two profiles:
1. test-cred : for accessing cloudburst-data-2 with an ID and secret key
2. test-ip: for accessing dcoa-gparton-manoj-object-internal-variant using instance profile based credentials.
```
root@ip-10-110-137-138:~# echo $AWS_SECRET_ACCESS_KEY
root@ip-10-110-137-138:~# echo $AWS_ACCESS_KEY_ID
root@ip-10-110-137-138:~# cat …
```

Remove object-credentials-location parameter

---

module/Makefile.in

Fixed merge conflict with upstream commit ed3a3bdb0d
Delphix specific entries like `debugdir` were breaking auto merges.
also changed Delphix specific use of `$(DESTDIR)$(INSTALL_MOD_PATH)` to `$(INSTALL_MOD_PATH)`
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6242/

Upstream merge
